# 2. Automatizar la obtención del eventing data

Una vez hemos entendido cómo están estructurados los datos, vamos a realizar automatizaciones para que sea un trabajo más fácil acceder a la información del partido que queramos. Vamos a ver paso a paso la automatización.

In [ ]:
import pandas as pd
import json

# 2.1. Automatizar la obtención de las competiciones y temporadas 
Vamos a empezar automatizando la obtención de los partidos de las diferentes  competiciones y las diferentes temporadas disponibles. Importamos el archivo competitions.json

In [ ]:
with open('/content/drive/MyDrive/Mi curso/Data/event_data/Statsbomb/data/competitions.json') as f:
    competitions = json.load(f)

Extraemos como hicimos anteriormente el competition_id y el competition_name de cada competición.

In [ ]:
competition_id = []
competition_name = []

for competition in competitions:
    if competition['competition_id'] not in competition_id:
        competition_id.append(competition['competition_id'])
        
    if competition['competition_name'] not in competition_name:
        competition_name.append(competition['competition_name'])

Utilizamos list() junto con zip() para que se vea cada id con su competición.

In [ ]:
list(zip(competition_id, competition_name))

[(16, 'Champions League'),
 (37, "FA Women's Super League"),
 (43, 'FIFA World Cup'),
 (11, 'La Liga'),
 (49, 'NWSL'),
 (2, 'Premier League'),
 (72, "Women's World Cup")]

Creamos un dataframe vacío para guardar la información del id y nombre de las competiciones.

In [ ]:
df_competition = pd.DataFrame()
df_competition

Empty DataFrame
Columns: []
Index: []

Una vez creado el dataframe vacío, creamos la columna 'id' y 'Competition'

In [ ]:
df_competition['id'] = competition_id
df_competition['Competition'] = competition_name
df_competition

   id              Competition
0  16         Champions League
1  37  FA Women's Super League
2  43           FIFA World Cup
3  11                  La Liga
4  49                     NWSL
5   2           Premier League
6  72        Women's World Cup

## 2.1.1. La función input() para hacer la automatización interactiva 
Para un mejor tratamiento de la información, vamos a utilizar una función en python que nos preguntará qué competición queremos analizar y lo que pongamos en el recuadro se guardará. Esta función es la función input()

In [ ]:
id_competition = input('Que competicion quieres analizar: ')

Que competicion quieres analizar: 11

Si miramos la variable id_competition vemos que se ha almacenado el id 11

In [ ]:
id_competition

'11'

Para obtener el resultado en formato numérico, utilizaremos la función int() para convertir a numérico.

In [ ]:
id_competition = int(input('Que competicion quieres analizar: '))

Que competicion quieres analizar: 11

In [ ]:
id_competition

11

Imprimimos el dataframe que contiene el id de la competiciones y su nombre, justo antes del input, para poder saber que diferentes competiciones podemos elegir.

In [ ]:
print(df_competition)
id_competition = int(input('Que competicion quieres analizar: '))

   id              Competition
0  16         Champions League
1  37  FA Women's Super League
2  43           FIFA World Cup
3  11                  La Liga
4  49                     NWSL
5   2           Premier League
6  72        Women's World Cup
Que competicion quieres analizar: 11

Adornamos un poco el print para que quede mejor estéticamente.

In [ ]:
print('*'*38)
print(df_competition, '\n')
id_competition = int(input('Que competicion quieres analizar: '))

**************************************
   id              Competition
0  16         Champions League
1  37  FA Women's Super League
2  43           FIFA World Cup
3  11                  La Liga
4  49                     NWSL
5   2           Premier League
6  72        Women's World Cup

Que competicion quieres analizar: 11

Vemos cómo de esta manera se nos muestra las diferentes competiciones y como el input() al final nos pregunta, qué competición queremos analizar. 

Realizamos el mismo procedimiento con el id de la temporada y el nombre de la temporada, que en este caso es la fecha.

In [ ]:
season_id = []
season_name = []

for season in competitions:

        if season['season_id'] not in season_id:
            season_id.append(season['season_id'])
        if season['season_name'] not in season_name:
            season_name.append(season['season_name'])

Nuevamente con list() y zip() lo podemos ver conjuntamente.

In [ ]:
list(zip(season_id, season_name))

[(4, '2018/2019'),
 (1, '2017/2018'),
 (2, '2016/2017'),
 (27, '2015/2016'),
 (26, '2014/2015'),
 (25, '2013/2014'),
 (24, '2012/2013'),
 (23, '2011/2012'),
 (22, '2010/2011'),
 (21, '2009/2010'),
 (41, '2008/2009'),
 (39, '2006/2007'),
 (37, '2004/2005'),
 (44, '2003/2004'),
 (76, '1999/2000'),
 (42, '2019/2020'),
 (3, '2018'),
 (40, '2007/2008'),
 (38, '2005/2006'),
 (30, '2019')]

Creamos también un dataframe que contiene los id y fechas de cada temporada.

In [ ]:
df_season = pd.DataFrame()
df_season['id'] = season_id
df_season['Season'] = season_name
df_season

    id     Season
0    4  2018/2019
1    1  2017/2018
2    2  2016/2017
3   27  2015/2016
4   26  2014/2015
5   25  2013/2014
6   24  2012/2013
7   23  2011/2012
8   22  2010/2011
9   21  2009/2010
10  41  2008/2009
11  39  2006/2007
12  37  2004/2005
13  44  2003/2004
14  76  1999/2000
15  42  2019/2020
16   3       2018
17  40  2007/2008
18  38  2005/2006
19  30       2019

Realizamos el mismo procedimiento que hicimos con las competiciones, para que se muestran los diferentes años, antes de seleccionar uno a través de input()

In [ ]:
print('*'*38)
print(df_season, '\n')
id_season = int(input('Que temporada quieres analizar: '))

**************************************
    id     Season
0    4  2018/2019
1    1  2017/2018
2    2  2016/2017
3   27  2015/2016
4   26  2014/2015
5   25  2013/2014
6   24  2012/2013
7   23  2011/2012
8   22  2010/2011
9   21  2009/2010
10  41  2008/2009
11  39  2006/2007
12  37  2004/2005
13  44  2003/2004
14  76  1999/2000
15  42  2019/2020
16   3       2018
17  40  2007/2008
18  38  2005/2006
19  30       2019

Que temporada quieres analizar: 4

Después de los dos inputs, se habrán guardado los valores seleccionados en las variables id_competition y id_season. Estos son el id seleccionado de la competición y temporada que corresponden a la Liga y la temporada 2018/2019

In [ ]:
id_competition, id_season

(11, 4)

## 2.1.2. Acceder a la información de los partidos 
Ahora que sabemos cómo seleccionar una competición y temporada, solo tenemos que sustituir sus valores en la ruta para poder acceder a la info de los partidos.

In [ ]:
with open('/content/drive/MyDrive/Mi curso/Data/event_data/Statsbomb/data/matches/11/4.json', encoding='utf-8') as f:
  matches = json.load(f)

Vamos a automatizar la ruta para cuando queramos usar otras competiciones y temporadas.

In [ ]:
'matches/' + str(id_competition) + '/'+ str(id_season) + '.json'

'matches/11/4.json'

Así es como quedaría nuestra ruta totalmente automatizada, lista para poder pasarle cualquier otra competición y temporada.

In [ ]:
with open('/content/drive/MyDrive/Mi curso/Data/event_data/Statsbomb/data/' + 'matches/' + str(id_competition) + '/'+ str(id_season) + '.json', encoding='utf-8') as f:
  matches = json.load(f)

In [ ]:
df = pd.json_normalize(matches)
df.head()

   match_id  match_date  ... referee.country.id  referee.country.name
0     16157  2019-02-02  ...              112.0                 Italy
1     16136  2019-01-20  ...              112.0                 Italy
2     16215  2019-03-17  ...              112.0                 Italy
3     16248  2019-04-06  ...              214.0                 Spain
4     16056  2018-11-11  ...              214.0                 Spain

[5 rows x 39 columns]

## 2.1.3. Juntar todo el código en una celda 
Vamos a juntar en una celda todo el código visto hasta ahora, para ir viendo cómo queda el resultado final.

In [ ]:
competition_id = []
competition_name = []

for competition in competitions:
    if competition['competition_id'] not in competition_id:
        competition_id.append(competition['competition_id'])
        
    if competition['competition_name'] not in competition_name:
        competition_name.append(competition['competition_name'])

df_competition = pd.DataFrame()
df_competition['id'] = competition_id
df_competition['Competition'] = competition_name

print('*'*38)
print(df_competition, '\n')
id_competition = int(input('Que competicion quieres analizar: '))

season_id = []
season_name = []

for season in competitions:

        if season['season_id'] not in season_id:
            season_id.append(season['season_id'])
        if season['season_name'] not in season_name:
            season_name.append(season['season_name'])

df_season = pd.DataFrame()
df_season['id'] = season_id
df_season['Season'] = season_name

print('*'*38)
print(df_season, '\n')
id_season = int(input('Que temporada quieres analizar: '))

with open('/content/drive/MyDrive/Mi curso/Data/event_data/Statsbomb/data/' + 'matches/' + str(id_competition) + '/'+ str(id_season) + '.json', encoding='utf-8') as f:
  matches = json.load(f)

df = pd.json_normalize(matches)
df.head()

**************************************
   id              Competition
0  16         Champions League
1  37  FA Women's Super League
2  43           FIFA World Cup
3  11                  La Liga
4  49                     NWSL
5   2           Premier League
6  72        Women's World Cup

Que competicion quieres analizar: 43
**************************************
    id     Season
0    4  2018/2019
1    1  2017/2018
2    2  2016/2017
3   27  2015/2016
4   26  2014/2015
5   25  2013/2014
6   24  2012/2013
7   23  2011/2012
8   22  2010/2011
9   21  2009/2010
10  41  2008/2009
11  39  2006/2007
12  37  2004/2005
13  44  2003/2004
14  76  1999/2000
15  42  2019/2020
16   3       2018
17  40  2007/2008
18  38  2005/2006
19  30       2019

Que temporada quieres analizar: 4

FileNotFoundError: ignored

Vemos que hemos tenido un error, dado que nos salen todas las temporadas una vez seleccionamos una competición, pero no todas las competiciones tienen varias temporadas. Hay competiciones que solo tiene una, como el caso de la copa del mundo. Por tanto tendremos que añadir un condicional más, cuando seleccionamos el id y los años de la temporada.

In [ ]:
competition_id = []
competition_name = []

for competition in competitions:
    if competition['competition_id'] not in competition_id:
        competition_id.append(competition['competition_id'])
        
    if competition['competition_name'] not in competition_name:
        competition_name.append(competition['competition_name'])

df_competition = pd.DataFrame()
df_competition['id'] = competition_id
df_competition['Competition'] = competition_name

print('*'*38)
print(df_competition, '\n')
id_competition = int(input('Que competicion quieres analizar: '))

season_id = []
season_name = []

for season in competitions:
  
  if season['competition_id'] == id_competition:

    if season['season_id'] not in season_id:
        season_id.append(season['season_id'])
    if season['season_name'] not in season_name:
        season_name.append(season['season_name'])

df_season = pd.DataFrame()
df_season['id'] = season_id
df_season['Season'] = season_name

print('*'*38)
print(df_season, '\n')
id_season = int(input('Que temporada quieres analizar: '))

with open('/content/drive/MyDrive/Mi curso/Data/event_data/Statsbomb/data/' + 'matches/' + str(id_competition) + '/'+ str(id_season) + '.json', encoding='utf-8') as f:
  matches = json.load(f)

df = pd.json_normalize(matches)
df.head()

**************************************
   id              Competition
0  16         Champions League
1  37  FA Women's Super League
2  43           FIFA World Cup
3  11                  La Liga
4  49                     NWSL
5   2           Premier League
6  72        Women's World Cup

Que competicion quieres analizar: 2
**************************************
   id     Season
0  44  2003/2004

Que temporada quieres analizar: 44

   match_id  match_date  ... referee.id  referee.name
0   3749257  2004-05-15  ...       1279          None
1   3749246  2004-03-28  ...       1279          None
2   3749153  2004-01-10  ...       1279          None
3   3749642  2004-02-28  ...       1279          None
4   3749358  2003-08-24  ...       1279          None

[5 rows x 34 columns]

Ahora hemos podido conseguir la información de los partidos de la competición y temporada que nos interesan. Pero vamos a arreglar un poco el dataframe para que quede mejor visualmente y se vea mejor la información del partido. 

Primero seleccionamos las columnas que nos interesan y realizamos una copia nueva del dataframe con .copy()

In [ ]:
columns = ['home_team.home_team_name','away_team.away_team_name','home_score','away_score',
           'match_id','match_date','competition.competition_name','competition_stage.name']

df = df[columns].copy()
df

   home_team.home_team_name  ... competition_stage.name
0                   Arsenal  ...         Regular Season
1                   Arsenal  ...         Regular Season
2                   Arsenal  ...         Regular Season
3                   Arsenal  ...         Regular Season
4             Middlesbrough  ...         Regular Season
5              Leeds United  ...         Regular Season
6                 Liverpool  ...         Regular Season
7                   Arsenal  ...         Regular Season
8          Blackburn Rovers  ...         Regular Season
9               Aston Villa  ...         Regular Season
10                  Arsenal  ...         Regular Season
11                  Arsenal  ...         Regular Season
12                  Arsenal  ...         Regular Season
13        Manchester United  ...         Regular Season
14                  Arsenal  ...         Regular Season
15          Manchester City  ...         Regular Season
16                  Chelsea  ...         Regular Season
17        Tottenham Hotspur  ...         Regular Season
18              Southampton  ...         Regular Season
19                  Arsenal  ...         Regular Season
20          Birmingham City  ...         Regular Season
21                  Arsenal  ...         Regular Season
22                  Arsenal  ...         Regular Season
23                  Arsenal  ...         Regular Season
24                  Arsenal  ...         Regular Season
25                  Arsenal  ...         Regular Season
26                  Arsenal  ...         Regular Season
27                  Arsenal  ...         Regular Season
28         Bolton Wanderers  ...         Regular Season
29        Charlton Athletic  ...         Regular Season
30  Wolverhampton Wanderers  ...         Regular Season
31                   Fulham  ...         Regular Season
32         Newcastle United  ...         Regular Season

[33 rows x 8 columns]

Ahora tiene una mejor pinta el dataframe. Con .columns vamos a cambiar el nombre a todas las columnas para que se entiendan mejor, colocamos el match_id como índice y ordenamos las fechas de menor a mayor.

In [ ]:
df.columns = ['home_team', 'away_team', 'home_score', 'away_score', 'match_id', 'match_date', 'competition','stage']
df.set_index('match_id', inplace=True)
df.sort_values('match_date', inplace=True)
df

                 home_team         away_team  ...  competition           stage
match_id                                      ...
15946            Barcelona  Deportivo Alavés  ...      La Liga  Regular Season
15956      Real Valladolid         Barcelona  ...      La Liga  Regular Season
15973            Barcelona            Huesca  ...      La Liga  Regular Season
15978        Real Sociedad         Barcelona  ...      La Liga  Regular Season
15986            Barcelona            Girona  ...      La Liga  Regular Season
15998              Leganés         Barcelona  ...      La Liga  Regular Season
16010            Barcelona   Athletic Bilbao  ...      La Liga  Regular Season
16023             Valencia         Barcelona  ...      La Liga  Regular Season
16029            Barcelona           Sevilla  ...      La Liga  Regular Season
16056            Barcelona        Real Betis  ...      La Liga  Regular Season
16073      Atlético Madrid         Barcelona  ...      La Liga  Regular Season
16079            Barcelona        Villarreal  ...      La Liga  Regular Season
16086             Espanyol         Barcelona  ...      La Liga  Regular Season
16095              Levante         Barcelona  ...      La Liga  Regular Season
16109            Barcelona        Celta Vigo  ...      La Liga  Regular Season
16120               Getafe         Barcelona  ...      La Liga  Regular Season
16131            Barcelona             Eibar  ...      La Liga  Regular Season
16136            Barcelona           Leganés  ...      La Liga  Regular Season
16149               Girona         Barcelona  ...      La Liga  Regular Season
16157            Barcelona          Valencia  ...      La Liga  Regular Season
16173      Athletic Bilbao         Barcelona  ...      La Liga  Regular Season
16182            Barcelona   Real Valladolid  ...      La Liga  Regular Season
16190              Sevilla         Barcelona  ...      La Liga  Regular Season
16196          Real Madrid         Barcelona  ...      La Liga  Regular Season
16205            Barcelona    Rayo Vallecano  ...      La Liga  Regular Season
16215           Real Betis         Barcelona  ...      La Liga  Regular Season
16231            Barcelona          Espanyol  ...      La Liga  Regular Season
16240           Villarreal         Barcelona  ...      La Liga  Regular Season
16248            Barcelona   Atlético Madrid  ...      La Liga  Regular Season
16265            Barcelona     Real Sociedad  ...      La Liga  Regular Season
16275     Deportivo Alavés         Barcelona  ...      La Liga  Regular Season
16289            Barcelona           Levante  ...      La Liga  Regular Season
16306            Barcelona            Getafe  ...      La Liga  Regular Season
16317                Eibar         Barcelona  ...      La Liga  Regular Season

[34 rows x 7 columns]

Nuevamente juntamos todo el código.

In [ ]:
competition_id = []
competition_name = []

for competition in competitions:
    if competition['competition_id'] not in competition_id:
        competition_id.append(competition['competition_id'])
        
    if competition['competition_name'] not in competition_name:
        competition_name.append(competition['competition_name'])

df_competition = pd.DataFrame()
df_competition['id'] = competition_id
df_competition['Competition'] = competition_name
df_competition.set_index('id', inplace=True)

print('*'*38)
print(df_competition, '\n')
id_competition = int(input('Que competicion quieres analizar: '))

season_id = []
season_name = []

for season in competitions:

  if season['competition_id'] == id_competition:

    if season['season_id'] not in season_id:
        season_id.append(season['season_id'])
    if season['season_name'] not in season_name:
        season_name.append(season['season_name'])

df_season = pd.DataFrame()
df_season['id'] = season_id
df_season['Season'] = season_name
df_season.set_index('id', inplace=True)

print('*'*38)
print(df_season, '\n')
id_season = int(input('Que temporada quieres analizar: '))

with open('/content/drive/MyDrive/Mi curso/Data/event_data/Statsbomb/data/' + 'matches/' + str(id_competition) + '/'+ str(id_season) + '.json', encoding='utf-8') as f:
  matches = json.load(f)

df = pd.json_normalize(matches)

columns = ['home_team.home_team_name','away_team.away_team_name','home_score','away_score',
           'match_id','match_date','competition.competition_name','competition_stage.name']

df = df[columns].copy()
df.columns = ['home_team', 'away_team', 'home_score', 'away_score', 'match_id', 'match_date', 'competition','stage']
df.set_index('match_id', inplace=True)
df.sort_values('match_date', inplace=True)
df

**************************************
                Competition
id
16         Champions League
37  FA Women's Super League
43           FIFA World Cup
11                  La Liga
49                     NWSL
2            Premier League
72        Women's World Cup

Que competicion quieres analizar: 49
**************************************
   Season
id
3    2018

Que temporada quieres analizar: 3

                       home_team  ...           stage
match_id                          ...
7430           Washington Spirit  ...  Regular Season
7443             Portland Thorns  ...  Regular Season
7445                 Utah Royals  ...  Regular Season
7444      North Carolina Courage  ...  Regular Season
7451      North Carolina Courage  ...  Regular Season
7456                 Sky Blue FC  ...  Regular Season
7457               Orlando Pride  ...  Regular Season
7519             Portland Thorns  ...  Regular Season
7521                 Sky Blue FC  ...  Regular Season
7520           Washington Spirit  ...  Regular Season
7522                Houston Dash  ...  Regular Season
7523               Seattle Reign  ...  Regular Season
7471               Orlando Pride  ...  Regular Season
7473                 Utah Royals  ...  Regular Season
7472               Seattle Reign  ...  Regular Season
7474           Chicago Red Stars  ...  Regular Season
7475      North Carolina Courage  ...  Regular Season
7477             Portland Thorns  ...  Regular Season
7478               Seattle Reign  ...  Regular Season
7476                 Sky Blue FC  ...  Regular Season
7479               Orlando Pride  ...  Regular Season
7524                Houston Dash  ...  Regular Season
7482      North Carolina Courage  ...  Regular Season
7480               Seattle Reign  ...  Regular Season
7485           Chicago Red Stars  ...  Regular Season
7483                 Utah Royals  ...  Regular Season
7484                 Sky Blue FC  ...  Regular Season
7486             Portland Thorns  ...  Regular Season
7487                 Utah Royals  ...  Regular Season
7490                 Sky Blue FC  ...  Regular Season
7493               Seattle Reign  ...  Regular Season
7492               Orlando Pride  ...  Regular Season
7494                Houston Dash  ...  Regular Season
7496                 Utah Royals  ...  Regular Season
7497           Chicago Red Stars  ...  Regular Season
7500               Orlando Pride  ...  Regular Season

[36 rows x 7 columns]

## 2.1.4. Crear la función que automatiza todo el proceso 
Ahora si obtenemos una información detallada de los partidos de los que dispones en cada competición y temporada. Vamos a crear finalmente nuestra función info_json(). Acordaros del path y cómo le añadimos el path para acceder a competitions y a matches.

In [ ]:
def info_jason(path):

  with open(path + '/competitions.json') as f:
    competitions = json.load(f)

  competition_id = []
  competition_name = []

  for competition in competitions:

      if competition['competition_id'] not in competition_id:
          competition_id.append(competition['competition_id'])
          
      if competition['competition_name'] not in competition_name:
          competition_name.append(competition['competition_name'])

  df_competition = pd.DataFrame()
  df_competition['id'] = competition_id
  df_competition['Competition'] = competition_name
  df_competition.set_index('id', inplace=True)

  print('*'*38)
  print(df_competition, '\n')
  id_competition = int(input('Que competicion quieres analizar: '))

  season_id = []
  season_name = []

  for season in competitions:

    if season['competition_id'] == id_competition:
          if season['season_id'] not in season_id:
              season_id.append(season['season_id'])
          if season['season_name'] not in season_name:
              season_name.append(season['season_name'])

  df_season = pd.DataFrame()
  df_season['id'] = season_id
  df_season['Season'] = season_name
  df_season.set_index('id', inplace=True)

  print('*'*38)
  print(df_season, '\n')
  id_season = int(input('Que temporada quieres analizar: '))

  with open(path + '/matches/' + str(id_competition) + '/'+ str(id_season) + '.json', encoding='utf-8') as f:
    matches = json.load(f)

  df = pd.json_normalize(matches)

  columns = ['home_team.home_team_name','away_team.away_team_name','home_score','away_score',
            'match_id','match_date','competition.competition_name','competition_stage.name']

  df = df[columns].copy()
  df.columns = ['home_team', 'away_team', 'home_score', 'away_score', 'match_id', 'match_date', 'competition','stage']
  df.set_index('match_id', inplace=True)
  df.sort_values('match_date', inplace=True)

  return df

Ahora con nuestra función sólo tendremos que pasar la ruta donde se encuentran los datos de statsbomb.

In [ ]:
info_jason('/content/drive/MyDrive/Mi curso/Data/event_data/Statsbomb/data')

**************************************
                Competition
id
16         Champions League
37  FA Women's Super League
43           FIFA World Cup
11                  La Liga
49                     NWSL
2            Premier League
72        Women's World Cup

Que competicion quieres analizar: 16
**************************************
       Season
id
4   2018/2019
1   2017/2018
2   2016/2017
27  2015/2016
26  2014/2015
25  2013/2014
24  2012/2013
23  2011/2012
22  2010/2011
21  2009/2010
41  2008/2009
39  2006/2007
37  2004/2005
44  2003/2004
76  1999/2000

Que temporada quieres analizar: 2

         home_team    away_team  ...       competition  stage
match_id                         ...
18244     Juventus  Real Madrid  ...  Champions League  Final

[1 rows x 7 columns]

Como veis, gracias a los inputs hemos seleccionado la Champions League y la temporada 2017/2018. De la cual obtenemos la información de la final. Ahora siempre que queramos info de un partido podremos acceder a la competiciones y temporada que nos interese. El objetivo real de todo esto, es obtener el id del partido para después en la carpeta events, extraer el eventing data de dicho partido. 

Pero sin extraer esta información no sabríamos qué partido pertenece a qué archivo. Ahora tenemos una sencilla manera de acceder a la información. 
##2.2. Automatización de la obtención del eventing data
Ahora que hemos llegado hasta el id del partido, sólo tenemos que usarlo dentro de with open() para acceder al eventing data de la carpeta eventing.

In [ ]:
with open('/content/drive/MyDrive/Mi curso/Data/event_data/Statsbomb/data/events/18244.json', encoding='utf-8') as f:
  data = json.load(f)

df = pd.json_normalize(data, sep='_')
df.head()

                                     id  ...  50_50_outcome_name
0  0436bcd0-e185-48c4-a6a8-1e7bc61d1032  ...                 NaN
1  e2711d47-5d90-4967-b531-5aa74ac03a20  ...                 NaN
2  7910a233-ec39-4332-9c39-f647bb837438  ...                 NaN
3  5dfef236-0be2-4c92-a814-9f07c23418af  ...                 NaN
4  da4e9849-f967-420b-9f34-bb3ea489aa40  ...                 NaN

[5 rows x 105 columns]

Accederemos a la columna type_name que contiene los diferentes eventos recogidos y le aplicamos un .unique() para ver los valores únicos.

In [ ]:
df.type_name.unique()

array(['Starting XI', 'Half Start', 'Pass', 'Ball Receipt*', 'Carry',
       'Clearance', 'Pressure', 'Block', 'Dribbled Past', 'Dribble',
       'Foul Committed', 'Foul Won', 'Miscontrol', 'Ball Recovery',
       'Dispossessed', 'Duel', 'Shot', 'Goal Keeper', 'Interception',
       'Offside', 'Tactical Shift', 'Injury Stoppage', 'Half End',
       'Bad Behaviour', 'Substitution', '50/50'], dtype=object)

Si quisiéramos analizar un evento en concreto solo tendremos que filtrar el dataframe por la columna type_name y pasándole el valor de alguno de sus eventos. Si pasamos 'Pass' obtendremos un dataframe con solo el evento pase.

In [ ]:
passes = df[df.type_name == 'Pass']
passes.head()

                                      id  ...  50_50_outcome_name
4   da4e9849-f967-420b-9f34-bb3ea489aa40  ...                 NaN
7   a461e051-ae06-4374-a1af-ae503cb677f3  ...                 NaN
10  e642b081-b999-4ec9-8825-48c50b1e8231  ...                 NaN
14  76e27dd2-34f0-4e52-ae66-876cf0249de5  ...                 NaN
16  cb0a7bf8-cc46-428f-b364-8b4a706638f7  ...                 NaN

[5 rows x 105 columns]

Si utilizamos la técnica de input(), imprimiendo primero los tipos de evento que tenemos, podremos dar la opción de seleccionar un evento y automáticamente se nos creará un dataframe con dicho evento.

In [ ]:
with open('/content/drive/MyDrive/Mi curso/Data/event_data/Statsbomb/data/events/18244.json', encoding='utf-8') as f:
  data = json.load(f)

df = pd.json_normalize(data, sep='_')

print(df.type_name.unique(), '\n')
event = input('Que evento quieres nalizar: ')
passes = df[df.type_name == event]
passes.head()

['Starting XI' 'Half Start' 'Pass' 'Ball Receipt*' 'Carry' 'Clearance'
 'Pressure' 'Block' 'Dribbled Past' 'Dribble' 'Foul Committed' 'Foul Won'
 'Miscontrol' 'Ball Recovery' 'Dispossessed' 'Duel' 'Shot' 'Goal Keeper'
 'Interception' 'Offside' 'Tactical Shift' 'Injury Stoppage' 'Half End'
 'Bad Behaviour' 'Substitution' '50/50']

Que evento quieres nalizar: Pass

                                      id  ...  50_50_outcome_name
4   da4e9849-f967-420b-9f34-bb3ea489aa40  ...                 NaN
7   a461e051-ae06-4374-a1af-ae503cb677f3  ...                 NaN
10  e642b081-b999-4ec9-8825-48c50b1e8231  ...                 NaN
14  76e27dd2-34f0-4e52-ae66-876cf0249de5  ...                 NaN
16  cb0a7bf8-cc46-428f-b364-8b4a706638f7  ...                 NaN

[5 rows x 105 columns]

## 2.2.1. Encapsulamos todo el proceso en la función
Encapsulamos todo el código dentro de la función event_data(), pero añadiremos el parámetro event=True en caso de que no quisiéramos seleccionar un evento y quisiéramos todos los eventos le pondremos el valor de False.

In [ ]:
def event_data(path, match_id, event=True):

  file_name = '/'+ str(match_id) + '.json'
  with open(path +  file_name, encoding='utf-8') as f:
    data = json.load(f)

  df = pd.json_normalize(data, sep='_')

  if event == True:
    print(df.type_name.unique(), '\n')
    event = input('Que evento quieres analizar: ')
    df = df[df.type_name == event]

  return df

Con el valor False del parámetro event no se ejecutará el input y obtendremos todos los eventos.

In [ ]:
event_data('/content/drive/MyDrive/Mi curso/Data/event_data/Statsbomb/data/events', 18244, False)

                                        id  ...  50_50_outcome_name
0     0436bcd0-e185-48c4-a6a8-1e7bc61d1032  ...                 NaN
1     e2711d47-5d90-4967-b531-5aa74ac03a20  ...                 NaN
2     7910a233-ec39-4332-9c39-f647bb837438  ...                 NaN
3     5dfef236-0be2-4c92-a814-9f07c23418af  ...                 NaN
4     da4e9849-f967-420b-9f34-bb3ea489aa40  ...                 NaN
...                                    ...  ...                 ...
3395  553ec774-2219-41cc-bb23-0c78217aae8d  ...                 NaN
3396  9e5dde0d-81cb-4152-b572-756b3c49f47e  ...                 NaN
3397  78e48f71-f9bb-46d8-8f27-2fa83c168c41  ...                 NaN
3398  7871c89b-c0d8-4c03-bfb1-f3a23aa77b93  ...                 NaN
3399  105c26bf-7bcf-4f31-b043-41c18673fe73  ...                 NaN

[3400 rows x 105 columns]

Una vez creadas las dos funciones info_json() y event_data(), podemos comprobar lo rápido que podemos extraer el eventing data del partido que nos interese.

In [ ]:
info_jason('/content/drive/MyDrive/Mi curso/Data/event_data/Statsbomb/data')

**************************************
                Competition
id
16         Champions League
37  FA Women's Super League
43           FIFA World Cup
11                  La Liga
49                     NWSL
2            Premier League
72        Women's World Cup

Que competicion quieres analizar: 43
**************************************
   Season
id
3    2018

Que temporada quieres analizar: 3

          home_team     away_team  ...     competition            stage
match_id                           ...
7525         Russia  Saudi Arabia  ...  FIFA World Cup      Group Stage
7577        Morocco          Iran  ...  FIFA World Cup      Group Stage
7576       Portugal         Spain  ...  FIFA World Cup      Group Stage
7578          Egypt       Uruguay  ...  FIFA World Cup      Group Stage
7531      Argentina       Iceland  ...  FIFA World Cup      Group Stage
...             ...           ...  ...             ...              ...
8652         Russia       Croatia  ...  FIFA World Cup   Quarter-finals
8655         France       Belgium  ...  FIFA World Cup      Semi-finals
8656        Croatia       England  ...  FIFA World Cup      Semi-finals
8657        Belgium       England  ...  FIFA World Cup  3rd Place Final
8658         France       Croatia  ...  FIFA World Cup            Final

[64 rows x 7 columns]

Ahora solo tenemos que pasara el id del partido que más nos interesa a la función event_data()

In [ ]:
event_data('/content/drive/MyDrive/Mi curso/Data/event_data/Statsbomb/data/events', 8658)

['Starting XI' 'Half Start' 'Pass' 'Ball Receipt*' 'Carry' 'Pressure'
 'Duel' 'Miscontrol' 'Clearance' 'Block' 'Ball Recovery' 'Dispossessed'
 'Foul Committed' 'Foul Won' 'Camera On' 'Interception' 'Dribble'
 'Camera off' 'Injury Stoppage' 'Dribbled Past' 'Own Goal For'
 'Own Goal Against' 'Shot' 'Goal Keeper' 'Shield' 'Player Off' 'Player On'
 'Half End' 'Referee Ball-Drop' 'Substitution' 'Error' 'Tactical Shift']

Que evento quieres analizar: Duel

                                        id  ...  substitution_replacement_name
22    395527d3-4a33-46a3-ac4f-ac84cc71c41a  ...                            NaN
82    031b927f-bbdc-473a-b68b-994450e53526  ...                            NaN
197   6a24ef5e-fba0-4d84-a670-42659748929f  ...                            NaN
210   ebef4729-ec57-4f37-b952-dcebf728ac67  ...                            NaN
307   2006cc2e-f437-4c40-a2fe-78d1463fedc5  ...                            NaN
334   d08f62ca-2e83-4b9e-b37b-04156e16da31  ...                            NaN
374   d9f116b0-3574-420c-91f5-e2b08de375ce  ...                            NaN
453   971ad2a9-11f0-4f1f-9437-325d2f74e870  ...                            NaN
482   c2527208-69e8-438e-acb8-138a2ca5bc0b  ...                            NaN
625   e42ba632-6045-4516-98c8-0e3a1ce1d818  ...                            NaN
636   ace7b4ac-62c6-4c04-8190-36c1295c5c0e  ...                            NaN
646   974e4ea1-79a8-44c4-af68-1a3e281b0fe3  ...                            NaN
663   702336dd-68d1-4c59-a122-5b8b4cd386f2  ...                            NaN
770   2fa7a1c6-5dda-4d9d-a22f-dd6a6963c25f  ...                            NaN
898   e96fb1de-91b1-4d40-8a50-db147b4b81aa  ...                            NaN
915   88ada183-56cb-43ae-85f9-0fb3490aec43  ...                            NaN
1010  f2bafa73-3a3b-4146-b463-36a441b5bcb4  ...                            NaN
1021  a536ee69-9c4c-4b2d-bc60-04b9bf788894  ...                            NaN
1082  99aa353a-0b57-4265-bdbe-9040f44d6822  ...                            NaN
1158  1f56e495-06bd-4d93-8a36-cfdaf03b0d60  ...                            NaN
1166  c9a70721-1a8c-4838-afc9-bd9ad9781719  ...                            NaN
1194  e62642fe-97d8-4f81-9211-a136ed51de93  ...                            NaN
1223  ec625539-4a62-4ac6-9b67-30fdd150abcf  ...                            NaN
1234  82222aaf-2c57-48fc-b735-007d77f838aa  ...                            NaN
1262  633dd275-2b9d-4c85-b476-b5e03a3dce12  ...                            NaN
1325  45bc02ff-c5bf-4619-9775-bd09e26b3d84  ...                            NaN
1337  d0333703-d681-4812-bfe5-f0a6781f39f4  ...                            NaN
1462  e6ad87fd-33c6-4ac6-a403-bd2ddcec9f4b  ...                            NaN
1519  0dcc6738-e95a-4bf5-9964-9463783c383b  ...                            NaN
1539  364daed2-7fed-4ce1-9339-80b8627dcd50  ...                            NaN
1549  25530954-c9db-4379-b55c-936ab7e71641  ...                            NaN
1621  cdb5c44f-a057-4892-95b3-07f985fdca4f  ...                            NaN
1627  a29acc73-38f5-4c75-812d-585bdb97b13b  ...                            NaN
1686  3886cdea-1877-4282-9892-1ae7c3db0dcb  ...                            NaN
1735  994834eb-955a-4c36-9035-8231beb398a7  ...                            NaN
1772  094af660-8595-4129-8b4d-8af107f06105  ...                            NaN
1790  5c30a384-6107-474f-a763-e5fa75f5f9a8  ...                            NaN
1921  ddb5d23a-d221-4ebe-b176-caa909aeef49  ...                            NaN
1956  151d1f81-5a04-4f0e-ad17-9a2814497549  ...                            NaN
2107  05a8978a-7d2e-496b-98b7-029a85187607  ...                            NaN
2169  2321f3b6-666d-45c2-b109-30d5c078c6be  ...                            NaN
2250  8d60a433-0220-4648-9e14-48d7d9793677  ...                            NaN
2263  c0315559-db8b-4851-a9de-6790875381a8  ...                            NaN
2538  a66bd370-5e71-4fa2-8936-b3de696c6df5  ...                            NaN
2542  8ec9543a-0616-4a7b-95a2-40d6d4c141eb  ...                            NaN
2652  9b4045d6-4033-4893-b282-28c8d6aad82f  ...                            NaN
2681  e764f38a-40b8-4ab0-9196-1cacedb2d479  ...                            NaN
2699  67365ada-c034-460e-9cbd-55e3dd9be6a3  ...                            NaN
2787  e33c9021-21df-4bee-a000-4007ab2571e6  ...                            NaN
2808  37acb986-331e-40c6-bdac-392626bd3f26  ...                            NaN
2859  57b7276a-efc3-45e1-92cd-984ab0dfd02c  ...                            NaN
2878  3b9a02fd-2eea-470a-948f-b53e33a0d223  ...                            NaN
2937  a82c5876-2dd9-47c9-a6c9-0969019c2231  ...                            NaN

[53 rows x 102 columns]

#2.3. Solucionar el problema de las coordenadas 
Ya vimos como teníamos la información de las coordenadas (x,y) de los eventos y como ellas venían dentro de una lista.

In [ ]:
import numpy as np

In [ ]:
event = event_data('/content/drive/MyDrive/Mi curso/Data/event_data/Statsbomb/data/events', 8656, False)
event.head()

                                     id  ...  injury_stoppage_in_chain
0  2c3fbeea-9fbf-43c7-8931-ed3037ede817  ...                       NaN
1  5179eca7-b788-4efd-ba40-352c8a3c45cf  ...                       NaN
2  8bfe88e1-5a20-49e9-87c8-c55a50729385  ...                       NaN
3  6b4d4b74-dd45-44b2-adec-a76ad9e1bc2d  ...                       NaN
4  f15b138e-9893-4819-94a0-56a1b57e1442  ...                       NaN

[5 rows x 107 columns]

Si accedemos a la información de la columna location podremos verlo.

In [ ]:
event.location

0                NaN
1                NaN
2                NaN
3                NaN
4       [61.0, 41.0]
            ...
2973     [5.0, 33.0]
2974     [5.0, 33.0]
2975    [18.0, 31.0]
2976             NaN
2977             NaN
Name: location, Length: 2978, dtype: object

También podemos verlo en la columna pass_end_location

In [ ]:
event.pass_end_location

0                NaN
1                NaN
2                NaN
3                NaN
4       [50.0, 42.0]
            ...
2973             NaN
2974             NaN
2975    [52.0, 25.0]
2976             NaN
2977             NaN
Name: pass_end_location, Length: 2978, dtype: object

Vamos hacer una list comprehension para ver cuantas columnas contiene la palabra location.

In [ ]:
cols = [col for col in event.columns if col.__contains__('location')]
cols

['location',
 'pass_end_location',
 'carry_end_location',
 'shot_end_location',
 'goalkeeper_end_location']

Estas son todas las columnas que vamos a tener que transformar.

In [ ]:
event[cols]

          location pass_end_location  ... shot_end_location goalkeeper_end_location
0              NaN               NaN  ...               NaN                     NaN
1              NaN               NaN  ...               NaN                     NaN
2              NaN               NaN  ...               NaN                     NaN
3              NaN               NaN  ...               NaN                     NaN
4     [61.0, 41.0]      [50.0, 42.0]  ...               NaN                     NaN
...            ...               ...  ...               ...                     ...
2973   [5.0, 33.0]               NaN  ...               NaN                     NaN
2974   [5.0, 33.0]               NaN  ...               NaN                     NaN
2975  [18.0, 31.0]      [52.0, 25.0]  ...               NaN                     NaN
2976           NaN               NaN  ...               NaN                     NaN
2977           NaN               NaN  ...               NaN                     NaN

[2978 rows x 5 columns]

La idea es crear una columna para las coordenadas de las x y de las y. Para ello creamos las columnas añadiendo el string '_x' e '_y' con una list comprehension.

In [ ]:
cols_x = [col + '_x' for col in event.columns if col.__contains__('location')]
cols_x

['location_x',
 'pass_end_location_x',
 'carry_end_location_x',
 'shot_end_location_x',
 'goalkeeper_end_location_x']

Vemos como se ha añadido una x a todas las columnas, realicemos el mismo procedimiento para las y.

In [ ]:
cols_y = [col + '_y' for col in event.columns if col.__contains__('location')]
cols_y

['location_y',
 'pass_end_location_y',
 'carry_end_location_y',
 'shot_end_location_y',
 'goalkeeper_end_location_y']

Con .loc accedemos a una coordenada

In [ ]:
event.loc[4, 'location']

[61.0, 41.0]

Con los índices accedemos el valor de las x

In [ ]:
event.loc[4, 'location'][0]

61.0

Con los índices accedemos al valor de las y

In [ ]:
event.loc[4, 'location'][1]

41.0

Utilizaremos la combinación de apply() más lambda para extraer la información de las x.

In [ ]:
event['location'].replace(np.nan, 0).apply(lambda x: x[0] if x !=0 else np.nan)

0        NaN
1        NaN
2        NaN
3        NaN
4       61.0
        ...
2973     5.0
2974     5.0
2975    18.0
2976     NaN
2977     NaN
Name: location, Length: 2978, dtype: float64

Haremos lo mismo para extraer la información de las y.

In [ ]:
event['location'].replace(np.nan, 0).apply(lambda x: x[1] if x !=0 else np.nan)

0        NaN
1        NaN
2        NaN
3        NaN
4       41.0
        ...
2973    33.0
2974    33.0
2975    31.0
2976     NaN
2977     NaN
Name: location, Length: 2978, dtype: float64


Ahora creamos las dos columnas, tanto 'location_x' y 'location_y' para ver cómo queda el resultado.

In [ ]:
event['location_x'] = event['location'].replace(np.nan, 0).apply(lambda x: x[0] if x !=0 else np.nan)
event['location_y'] = event['location'].replace(np.nan, 0).apply(lambda x: x[1] if x !=0 else np.nan)

event[['location_x', 'location_y']]

      location_x  location_y
0            NaN         NaN
1            NaN         NaN
2            NaN         NaN
3            NaN         NaN
4           61.0        41.0
...          ...         ...
2973         5.0        33.0
2974         5.0        33.0
2975        18.0        31.0
2976         NaN         NaN
2977         NaN         NaN

[2978 rows x 2 columns]

Para hacer el mismo cambio a todas las columnas que contienen location o unas coordenadas, utilizamos un bucle for.

In [ ]:
for i in range(len(cols)):
  event[cols_x[i]] = event[cols[i]].replace(np.nan, 0).apply(lambda x: x[0] if x !=0 else np.nan)
  event[cols_y[i]] = event[cols[i]].replace(np.nan, 0).apply(lambda x: x[1] if x !=0 else np.nan)

Ahora podemos ver el resultado final de cómo han quedado las coordenadas de las y.

In [ ]:
event[cols_y]

      location_y  ...  goalkeeper_end_location_y
0            NaN  ...                        NaN
1            NaN  ...                        NaN
2            NaN  ...                        NaN
3            NaN  ...                        NaN
4           41.0  ...                        NaN
...          ...  ...                        ...
4161        21.0  ...                        NaN
4162        21.0  ...                        NaN
4163         NaN  ...                        NaN
4164         NaN  ...                        NaN
4165         NaN  ...                        NaN

[4166 rows x 5 columns]

## 2.3.1. Automatizar todo el proceso 
Encapsulamos todo el código dentro de la función coordinates()

In [ ]:
def coordinates(df):

  cols = [col for col in df.columns if col.__contains__('location')]
  cols_x = [col + '_x' for col in df.columns if col.__contains__('location')]
  cols_y = [col + '_y' for col in df.columns if col.__contains__('location')]

  for i in range(len(cols)):
    df[cols_x[i]] = df[cols[i]].replace(np.nan, 0).apply(lambda x: x[0] if x !=0 else np.nan)
    df[cols_y[i]] = df[cols[i]].replace(np.nan, 0).apply(lambda x: x[1] if x !=0 else np.nan)

  df.drop(cols, axis=1, inplace=True)

  return df

Una vez creada la función coordinates() realmente la colocaremos dentro de la función event_data() para así cuando extraemos el eventing data ya esté solucionado el problema de las coordenadas.

In [ ]:
def event_data(path, match_id, event=True):

  file_name = '/'+ str(match_id) + '.json'
  with open(path +  file_name, encoding='utf-8') as f:
    data = json.load(f)

  df = pd.json_normalize(data, sep='_')
  df = coordinates(df)
  
  if event == True:
    print(df.type_name.unique(), '\n')
    event = input('Que evento quieres analizar: ')
    df = df[df.type_name == event]

  return df

Si ejecutamos nuestra función podemos ver el resultado final

In [ ]:
pases = event_data('/content/drive/MyDrive/Mi curso/Data/event_data/Statsbomb/data/events', 8656)

['Starting XI' 'Half Start' 'Pass' 'Ball Receipt*' 'Carry' 'Pressure'
 'Miscontrol' 'Ball Recovery' 'Foul Committed' 'Foul Won' 'Interception'
 'Camera On' 'Dispossessed' 'Duel' 'Block' 'Shot' 'Goal Keeper'
 'Clearance' 'Dribbled Past' 'Dribble' 'Half End' 'Bad Behaviour'
 'Injury Stoppage' 'Player Off' 'Player On' 'Substitution' 'Shield'
 'Tactical Shift' 'Camera off' 'Referee Ball-Drop']

Que evento quieres analizar: Pass

In [ ]:
pases[['location_x', 'location_y', 'pass_end_location_x', 'pass_end_location_y']]

      location_x  location_y  pass_end_location_x  pass_end_location_y
4           61.0        41.0                 42.0                 32.0
7           43.0        32.0                 51.0                 59.0
11          53.0        60.0                 44.0                 48.0
13          44.0        48.0                 49.0                 61.0
17          51.0        62.0                 75.0                 64.0
...          ...         ...                  ...                  ...
4149        68.0        30.0                 78.0                 53.0
4153        75.0        48.0                 79.0                 18.0
4156        85.0        22.0                 89.0                 27.0
4158        88.0        24.0                113.0                 44.0
4162        19.0        21.0                 43.0                 28.0

[1193 rows x 4 columns]