#**2. Limpieza y transformación de datos Parte 3**

En el tema limpieza y transformación de datos parte 2 del modul 1, empezamos a introducirnos en los bucles for y condicionales, de cómo la combinación de ambos nos permitirán automatizar procesos más complejos, como el de la selección y tratamiento automático de columnas. También vimos diferentes técnicas a la hora de utilizar el bucle for, como la técnica de crear una lista vacía. Si no lo recuerdas bien o todavía te cuesta un poco, te recomiendo volver a repasar los vídeos y teoría de ese tema, ya que ahora vamos a conocer unas técnicas todavía más avanzadas que parten de lo que vimos en limpieza de datos parte 2. Tranquilos este tema es el último en el que tocaremos concepto avanzados de programación con  python. De aquí en adelante ya solo pondremos en práctica todo lo aprendido en cuanto a fundamento de programación y nos centraremos en la creación de automatizaciones y herramientas para el análisis. Así que vayamos a por las últimas técnica que os elevarán por encima del resto, que son las list comprehension y los bucles for anidados.

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Mi curso/Data/clean_data/nba_19_pergame.csv')

# 2.1 Bucle for anidado
Como su nombre indica, significa un bucle for dentro de otro bucle for. Este concepto es muy avanzado, por lo que se tiene que tener bien claro el entendimiento del bucle for. A veces los bucles for anidados, nos ayudaran a solucionar problemas, que sin ellos no podríamos automatizarlos. Repasemos un momento el bucle for antes de pasar a ver el bucle for anidado. Ya sabemos que el bucle for nos permite recorrer una lista de valores. 

Ejemplo de bucle for, sobre un rango de valores con range():

In [ ]:
for i in range(5):
  print(i)

0
1
2
3
4

Ejemplo de bucle for en el que iteramos sobre las cinco primeras columnas del dataframe nba:

In [ ]:
for col in df.columns[:5]:
  print(col)

Player
Pos
Age
Tm
G

Acordaros siempre de la estructura básica de un bucle for, donde tenemos las palabras reservadas for e in, el iterador al cual le ponemos el nombre que queramos y sobre que estamos iterando. 

Pasemos a ver paso a paso cómo funciona un bucle for anidado y cómo nos puede ayudar en los problemas del mundo real. Un bucle for anidado no es más que un bucle dentro de otro bucle. Para entender el funcionamiento interno de un bucle for anidado, tenemos que verlo como si fueran las agujas de un reloj. Tenemos la aguja de las horas, que se mueve una vez a cada hora, pero por cada hora, la aguja de los minutos da la vuelta entera. Una vez realizada la vuelta de la aguja de los minutos, la aguja de las horas se mueve otra vez y se vuelve a repetir el mismo proceso con la aguja de los minutos. Esta sería la idea detrás del bucle for anidado, veámoslo más claro con un ejemplo. 

Crearemos dos listas, por las que iterará el primero y el segundo bucle, tendrán valores del 1 al 3 con range(1,4)

In [ ]:
primer_bucle = list(range(1,4))
print(primer_bucle)
segundo_bucle = list(range(1,4))
print(segundo_bucle)

[1, 2, 3]
[1, 2, 3]

Utilizaremos la función print(), para ver que sucede dentro de los bucles. Con ``print('--'*10)`` es simplemente un truco para añadir líneas y que quede mejor visualmente el resultado.

In [ ]:
for i in primer_bucle:

    print('--'*10)
    print('Primer bucle, iteración número:', i)
    print('--'*10)

    for j in segundo_bucle:
        print('Valor segundo bucle: ', j)

--------------------
Primer bucle, iteración número: 1
--------------------
Valor segundo bucle:  1
Valor segundo bucle:  2
Valor segundo bucle:  3
--------------------
Primer bucle, iteración número: 2
--------------------
Valor segundo bucle:  1
Valor segundo bucle:  2
Valor segundo bucle:  3
--------------------
Primer bucle, iteración número: 3
--------------------
Valor segundo bucle:  1
Valor segundo bucle:  2
Valor segundo bucle:  3

Primero, el primer bucle itera por su lista de valores, una vez pasa al primer valor de las lista que es el 1, pasamos a iterar sobre todos los valores en el segundo bucle. Una vez recorrido todos los valores del segundo bucle, pasamos de nuevo  al siguiente valor del primer bucle que será el 2. Así hasta haber completado todos los valores del primer bucle.  Como sucedía con las agujas del reloj, las horas serían los valores del primer bucle y los minutos los del segundo bucle.  No pasamos a  la siguiente hora, hasta que de la vuelta a todos los minutos.

Con la técnica de print(), vemos que sucede internamente en el bucle anidado y qué valores está iterando. Podemos ver claramente, cómo una vez iterado en el primer valor del primer bucle, iteramos sobre todo los valores del segundo bucle.

Acordaros que en cada iteración de un bucle for, ejecutamos todo el código que hay dentro de él, si en este caso tenemos otro  bucle for en su interior, a cada iteración del primer bucle, se ejecutará todo el bucle en el interior y así sucesivamente. Repite el proceso con ejemplos como el que acabamos de ver, para que interiorices y entiendas lo que pasa dentro del bucle for anidado.

Por ejemplo, vamos a utilizar el bucle for anidado, donde en el primer bucle iteramos sobre el valor de las 3 primeras columnas y el bucle anidado sobre los 3 primeros valores de cada columna.

In [ ]:
for col in df.columns[:3]:
  
  print('-'*15)
  print(col)
  print('-'*15)

  for i in range(3):
    print(df.loc[i, col])

---------------
Player
---------------
Steven Adams
Bam Adebayo
LaMarcus Aldridge
---------------
Pos
---------------
C
PF
C
---------------
Age
---------------
26
22
34

Fijaros como en el primer bucle, obtenemos la primera columnas e imprimimos su nombre  y en el segundo bucle, obtenemos  los tres valores de la columna, una vez finalizado el segundo bucle, volvemos al primer for para pasar a la siguiente columna y nuevamente en el segundo for volvemos a iterar por los tres valores de la segunda columna.

 En la primera iteración, esto será lo que está pasando dentro del segundo for

In [ ]:
print(df.loc[0, 'Player'])
print(df.loc[1, 'Player'])
print(df.loc[2, 'Player'])

Steven Adams
Bam Adebayo
LaMarcus Aldridge

Donde la columna será la misa, pero el valor de las filas irá cambiando. Esta técnica de bucle for anidado, nos será muy útil en el módulo 3, cuando tengamos que automatizar la visualización de datos de eventing y tracking. Ahora vamos a ver cómo nos puede ayudar para resolver un problema de tratamiento de datos. Ya sabéis que siempre que os enseño un concepto de python, lo enseño junto a su aplicabilidad. 

## 2.1.1. El problema de los duplicados. 

A veces en los datos nos podemos encontrar con duplicados, que no es más que una fila del dataframe que está repetida con exactamente los mismo valores. Para estos casos donde toda la fila tiene los mismo valores, podemos utilizar un función de pandas .drop_duplicates(). Esta función automáticamente eliminará las filas repetidas. Pero nosotros tenemos un problema un poco más complejo que ese. 

En el dataframe de las estadísticas de todos los jugadores de la NBA de toda una temporada, nos surge un problema a resolver y es que los jugadores que han jugado en varios equipos durante la temporada, los tendremos duplicados. Como por ejemplo, el caso de Trevor Ariza, que jugó en Portland y en Sacramento. Si filtramos el dataframe por su nombre, podremos verlo.

In [ ]:
df[df.Player == 'Trevor Ariza']

          Player Pos  Age   Tm   G  GS  ...  AST  STL  BLK  TOV   PF   PTS
18  Trevor Ariza  SF   34  TOT  53  21  ...  1.7  1.3  0.3  1.1  2.1   8.0
19  Trevor Ariza  SF   34  SAC  32   0  ...  1.6  1.1  0.2  0.9  2.0   6.0
20  Trevor Ariza  SF   34  POR  21  21  ...  2.0  1.6  0.4  1.3  2.3  11.0

[3 rows x 29 columns]

Como podemos ver en la columna Tm, que representa el equipo, vemos los valores de SAC de Sacramento y POR de Portland. Pero aparece otro valor que es TOT. Este último, representa el total de las estadísticas que obtuvo el jugador, en los dos equipos. Para evitarnos problemas de duplicados, a los jugadores que les pase esto, nos quedaremos con los valores del  jugador donde Tm = 'TOT', eliminando la de los otros equipos. ¿Cómo hacemos esto? Gracias a los bucles for anidados, podremos solucionar este problema y automatizarlo, para cuando utilicemos otras temporadas, ya que aparecerá el mismo problema. 

Cuando tenemos un problema así a resolver, tenemos que partirlo en pequeños problemas, Primero tenemos que saber a qué jugadores les pasa esto. Para ello  filtramos el dataframe por los valores en la columna Tm que sean igual a  'TOT' y de ese filtrado nos quedamos con la columna Player que contiene el nombre de los jugadores y utilizamos .values para obtener los valores en formato lista.

In [ ]:
names = df[df.Tm =='TOT'].Player.values
names

array(['Trevor Ariza', 'Keita Bates-Diop', 'Kent Bazemore',
       'Malik Beasley', 'Jordan Bell', 'Dragan Bender', 'Jonah Bolden',
       'Trey Burke', 'Alec Burks', 'Bruno Caboclo', 'DeMarre Carroll',
       'Willie Cauley-Stein', 'Chris Chiozza', 'Gary Clark',
       'Jordan Clarkson', 'Tyler Cook', 'Robert Covington',
       'Allen Crabbe', 'Jae Crowder', 'Troy Daniels', 'Dewayne Dedmon',
       'Gorgui Dieng', 'Andre Drummond', 'James Ennis', 'Jacob Evans',
       'Dante Exum', 'Wenyen Gabriel', 'Treveon Graham', 'Jeff Green',
       'Donta Hall', 'Maurice Harkless', 'John Henson',
       'Juan Hernangómez', 'Solomon Hill', 'Reggie Jackson',
       'James Johnson', 'Tyler Johnson', 'Michael Kidd-Gilchrist',
       'Brandon Knight', 'Alex Len', 'Jordan McRae', 'Marcus Morris',
       'Markieff Morris', 'Shabazz Napier', 'Zach Norvell',
       'Jabari Parker', 'Glenn Robinson III', 'Jerome Robinson',
       "D'Angelo Russell", 'Caleb Swanigan', 'Jeff Teague',
       'Anthony Tolliver', 'Jarrod Uthoff', 'Jarred Vanderbilt',
       'Noah Vonleh', 'Dion Waiters', 'Derrick Walton', 'Paul Watson',
       'Andrew Wiggins', 'Marvin Williams'], dtype=object)

Ahora tenemos la variable names, que contiene una lista con el nombre de los jugadores duplicados. Pero lo que realmente nos interesa es saber los índices de las filas de estos jugadores. Para obtener los índices de los jugadores duplicados, filtraremos el dataset por su nombre y utilizaremos el atributo .index seguido .values, para obtener los índices de las filas en formato lista.  Por ejemplo con  'Trevor Ariza'  obtenemos  3 índices.

In [ ]:
df[df.Player =='Trevor Ariza'].index.values

array([18, 19, 20])

Podemos ver que hay tres filas con el mismo nombre, la  18, 19 y  20. Realizaremos un bucle for a través de la lista names, donde tenemos los nombres de los jugadores duplicados y cada uno de los nombres que obtendremos de la iteración, se la pasaremos al dataframe, para ir extrayendo todos los índices duplicados como hemos hecho en ejemplo de  'Trevor Ariza'  .

Para ir guardando todos los índices duplicados, utilizaremos la técnica de la lista vacía. Crearemos una lista vacía que la llamaremos idx, donde con la función .append(), iremos añadiendo los índices de los duplicados.

In [ ]:
# Creamos lista vacía donde añadiremos los índices
idx=[]

# Iteramos sobre los nombres de la lista names
for name in names:
    # Añadimos a la lista vacía los índices de las filas igual a ese nombre
    idx.append(df[df.Player == name].index.values)

Después de ejecutar el bucle for, si miramos los tres primeros valores  de nuestra lista idx, que contienen los índices, vemos cómo hemos obtenido los índices de cada jugador duplicado.

In [ ]:
idx[:3]

[array([18, 19, 20]), array([31, 32, 33]), array([36, 37, 38])]

También es importante observar que nuestra lista idx, es una lista de listas. Los índices de cada jugador están dentro de una lista y estás lista a su vez estás dentro de las lista idx.

Ahora tenemos una lista con el valor de todos los índices duplicados, pero nosotros solo queremos quedarnos con los índices cuando el valor de Tm sea igual a 'TOT' y eliminar el resto de índices que contienen las estadísticas de los equipos por donde paso. Creamos la variable idx_good que contendrá los índices con los que nos queremos quedar.

In [ ]:
idx_good = df[df.Tm == 'TOT'].index.values
idx_good

array([ 18,  31,  36,  41,  45,  49,  62,  92,  95, 100, 107, 115, 122,
       126, 130, 142, 145, 148, 153, 159, 165, 172, 183, 192, 196, 199,
       216, 234, 244, 252, 258, 272, 276, 285, 315, 326, 331, 345, 350,
       370, 411, 433, 436, 450, 458, 480, 517, 520, 531, 561, 565, 577,
       589, 594, 599, 605, 611, 619, 627, 634])

Con la lista de los  índices duplicados idx y la lista con los índices que nos queremos quedar idx_good , realizaremos el bucle for anidado. Te lo explicaré paso a paso. Como hemos visto, hemos obtenido los índices duplicados, pero es una lista de listas, significa que en su interior tiene listas con los índices de cada jugador duplicado. 

El primero valor de la lista idx contiene a su vez un lista con tres índices, que corresponden a los índices de Trevor Ariza

Para poder acceder a los valores de una lista de listas, utilizaremos la técnica de los dos corchetes que vimos en el tema de estructuras de datos del módulo 1. De esta manera podremos acceder a los valores:

In [ ]:
#Primer valor de la lista
idx[0][0]

18

In [ ]:
# Segundo valor de la lista
idx[0][1]

19

In [ ]:
# Tercer valor de la lista
idx[0][2]

20

Si queremos acceder dentro de los valores de la lista, necesitaremos el bucle anidado, ya que el primer bucle, itera por cada una de las listas en la lista idx y el segundo en cada uno de los valores de la lista del primer bucle. Veámoslo con un ejemplo donde haremos el bucle for sobre las dos primeras listas dentro de la lista idx.

In [ ]:
# Iteramos sobre las lista de listas
for i in idx[:2]:
    print('lista',i)
    # Iteramos sobre el valor de la lista del primer bucle
    for j in i:
        print('valores lista', j)

lista [18 19 20]
valores lista 18
valores lista 19
valores lista 20
lista [31 32 33]
valores lista 31
valores lista 32
valores lista 33

Como vemos, en este ejemplo estamos accediendo con un  bucle for anidado, a los valores de la primera y segunda lista de la lista idx. Entonces, de los  valores del segundo bucle que son la j, solo nos queremos quedarnos con el índice 18 y 31. Para ello, en el segundo bucle utilizaremos un condicional if. Si el índice no está en la lista de idx_good que contiene los índices que queremos mantener, los añadiremos a la lista vacía drop_idx con .append().

Al finalizar el bucle, tendremos una lista con los valores de los índices que queremos eliminar del dataframe, en la variable drop_idx. Una vez entendido lo que sucede dentro de los bucles, en el ejemplo con las dos primeras listas, realicemos el bucle sobre todas las listas.

In [ ]:
# Creamos la lista vacía donde irán los índices que queremos borrar
drop_idx = []
# El primer bucle itera sobre la lista de los índices duplicados 
for i in idx:
    # El segundo bucle itera sobre los valores de cada lista
    for j in i:
        if j not in idx_good:
            drop_idx.append(j)

Si volvemos a mirar los dos primeros valores de idx, que contiene el valor de los índices duplicados, que corresponden a los jugadores Trevor Ariza y Keita Bates-Diop

In [ ]:
idx[:2]

[array([18, 19, 20]), array([31, 32, 33])]

Podemos ver estos índices al filtrar el dataframe por sus nombres.

In [ ]:
df[(df.Player == 'Trevor Ariza') | (df.Player == 'Keita Bates-Diop')]

              Player    Pos  Age   Tm   G  GS  ...  AST  STL  BLK  TOV   PF   PTS
18      Trevor Ariza     SF   34  TOT  53  21  ...  1.7  1.3  0.3  1.1  2.1   8.0
19      Trevor Ariza     SF   34  SAC  32   0  ...  1.6  1.1  0.2  0.9  2.0   6.0
20      Trevor Ariza     SF   34  POR  21  21  ...  2.0  1.6  0.4  1.3  2.3  11.0
31  Keita Bates-Diop  PF-SF   24  TOT  44   0  ...  0.7  0.4  0.5  0.4  1.0   6.5
32  Keita Bates-Diop     PF   24  MIN  37   0  ...  0.8  0.5  0.5  0.4  1.0   6.8
33  Keita Bates-Diop     SF   24  DEN   7   0  ...  0.0  0.3  0.6  0.4  1.0   5.3

[6 rows x 29 columns]

Nosotros nos queremos quedar con el índice 18 de Trevor Ariza y el 31 de Keita Bates-Diop. Por lo tanto los demás índices deberían estar en la variable donde con el bucle for anidado, añadimos los índices a eliminar. Como hemos eliminado dos índices de los dos jugadores miremos los 4 primeros valores de la variable drop_idx.

In [ ]:
drop_idx[:4]

[19, 20, 32, 33]

Como podemos ver están el índice 19, 20 de Trevor Ariza y el 32, 33 de Keita. Ahora solo tenemos que usar la función .drop(), pasándole por parámetro la lista de índices que queremos eliminar y especificar el parámetro axis=0, de esta manera indicamos que estamos eliminando filas.

In [ ]:
df.drop(drop_idx, axis=0, inplace=True)

Ahora cuando volvamos a visualizar el dataframe, podemos ver que ya no nos sale el jugador duplicado, en los diferentes equipos donde jugó y que la columna Tm es tiene el valor de  'TOT'

In [ ]:
df[(df.Player == 'Trevor Ariza') | (df.Player == 'Keita Bates-Diop')]

              Player    Pos  Age   Tm   G  GS  ...  AST  STL  BLK  TOV   PF  PTS
18      Trevor Ariza     SF   34  TOT  53  21  ...  1.7  1.3  0.3  1.1  2.1  8.0
31  Keita Bates-Diop  PF-SF   24  TOT  44   0  ...  0.7  0.4  0.5  0.4  1.0  6.5

[2 rows x 29 columns]

Ahora ya tenemos el problema de los duplicados resuelto. Si hubiésemos hecho un análisis de los jugadores sin tratar esta parte, habríamos tenido problemas al encontrarnos con jugadores que aparecían múltiples veces y como realmente no eran filas que sus valores eran idénticos, no podíamos utilizar .drop_duplicates(). Hemos tenido que recurrir a los bucles for anidados para la solucionar el problema.

Este problema es más avanzado, pero la lógica de programación y de resolución de problemas con este ejercicio, no tiene precio. Practicalo tantas veces como sea necesario hasta que lo interiorices. 

## 2.1.2 Automatización

El dataframe utilizado, son datos extraídos de basketball-reference. Eso significa que siempre que tratemos con datos de la información de todos los jugadores siempre nos encontraremos con este problema. ¿Qué significa esto? Pues que tendremos que crear una automatización para quitarnos de encima este problema, ya que será un problema recurrente al utilizar estos datos.  

Vamos a encapsular todo el proceso del bucle for anidado dentro una función que llamaremos drop_duplicate_player(), a la que por parámetro le pasaremos el dataframe y la función nos retorna el dataframe sin jugadores duplicados.

In [ ]:
def drop_duplicate_player(df):
    
    # Nombres de los jugadores duplicados
    names = df[df.Tm =='TOT'].Player.values
    
    # Los índices con los que nos queremos quedar
    idx_good = df[df.Tm =='TOT'].index.values
    
    # Creamos lista vacía donde añadiremos los índices
    idx=[]

    # Iteramos sobre los nombre de la lista names
    for name in names:
        # Añadimos a la lista vacía los índices de las filas igual a ese nombre
        idx.append(df[df.Player == name].index.values)
        
    # Creamos la lista vacía donde irán los índices que queremos borrar
    drop_idx = []
    
    # El primer bucle itera sobre la lista de los índices duplicados 
    for i in idx:
        # El segundo bucle itera sobre los valores de cada lista del primer bucle
        for j in i:
            if j not in idx_good:
                drop_idx.append(j)
                
    df.drop(drop_idx, axis=0, inplace=True)
                
    return df

Ahora si importamos de nuevo los datos, los cuales tendrán el problema de los duplicados y le pasamos el dataframe a la función drop_duplicate_player() obtendremos automáticamente el dataframe sin jugadores duplicados.

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Mi curso/Data/clean_data/nba_19_pergame.csv')
df[(df.Player == 'Trevor Ariza') | (df.Player == 'Keita Bates-Diop')]

              Player    Pos  Age   Tm   G  GS  ...  AST  STL  BLK  TOV   PF   PTS
18      Trevor Ariza     SF   34  TOT  53  21  ...  1.7  1.3  0.3  1.1  2.1   8.0
19      Trevor Ariza     SF   34  SAC  32   0  ...  1.6  1.1  0.2  0.9  2.0   6.0
20      Trevor Ariza     SF   34  POR  21  21  ...  2.0  1.6  0.4  1.3  2.3  11.0
31  Keita Bates-Diop  PF-SF   24  TOT  44   0  ...  0.7  0.4  0.5  0.4  1.0   6.5
32  Keita Bates-Diop     PF   24  MIN  37   0  ...  0.8  0.5  0.5  0.4  1.0   6.8
33  Keita Bates-Diop     SF   24  DEN   7   0  ...  0.0  0.3  0.6  0.4  1.0   5.3

[6 rows x 29 columns]

Vemos como nuevamente tenemos los jugadores duplicados. Pasemos a utilizar ahora nuestra función.

In [ ]:
df = drop_duplicate_player(df)
df[(df.Player == 'Trevor Ariza') | (df.Player == 'Keita Bates-Diop')]

              Player    Pos  Age   Tm   G  GS  ...  AST  STL  BLK  TOV   PF  PTS
18      Trevor Ariza     SF   34  TOT  53  21  ...  1.7  1.3  0.3  1.1  2.1  8.0
31  Keita Bates-Diop  PF-SF   24  TOT  44   0  ...  0.7  0.4  0.5  0.4  1.0  6.5

[2 rows x 29 columns]

Gracias a nuestra función, ya no nos tendremos que preocupar más del problema de los jugadores en múltiples equipos. 

## 2.1.3 Funcion dentro de otra función

Ya hemos automatizado el problema de los jugadores en múltiples equipos, pero recordad que el dataframe que estamos tratando, el de las estadísticas por partido de los jugadores de la NBA de la temporada 2019-2020 venía con problemas en la columna Player, la columna Pos y problema de valores NAN. Estos problemas los tratamos en el módulo 1 en tema limpieza de datos parte 1. En aquel tema realizamos una función que solventaba este problema. Vamos a traer de nuevo aquella función.

In [ ]:
def clean_data(file_path):

    df = pd.read_csv(file_path)
    df.fillna(0, inplace=True)
    df['Player'] = df.Player.apply(lambda x: x.split('\\')[0])
    df['Pos'] = df.Pos.apply(lambda x: x.split('-')[0])
    
    return df

Ahora vamos a ver una técnica muy común en programación, que es colocar una función dentro de otra función. Primero volvemos a importar los datos, ya que para el bucle for anidado utilizamos el dataframe que estaba en la carpeta de clean_data. Por tanto volamos a traer el dataframe que se encuentra en la carpeta de raw_data.

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Mi curso/Data/raw_data/nba_2019_20_pergame.csv')
df.head()

   Rk                              Player Pos  Age  ...  BLK  TOV   PF   PTS
0   1              Steven Adams\adamsst01   C   26  ...  1.1  1.5  1.9  10.9
1   2               Bam Adebayo\adebaba01  PF   22  ...  1.3  2.8  2.5  15.9
2   3         LaMarcus Aldridge\aldrila01   C   34  ...  1.6  1.4  2.4  18.9
3   4            Kyle Alexander\alexaky01   C   23  ...  0.0  0.5  0.5   1.0
4   5  Nickeil Alexander-Walker\alexani01  SG   21  ...  0.2  1.1  1.2   5.7

[5 rows x 30 columns]

Podemos ver como nos aparece de nuevo el problema en el nombre de los jugadores. Lo que tenemos que hacer es modificar el final de la función clean_data() que creamos. Cuando ya hemos solucionado los problemas en los datos, en vez de devolver con return la variable df, añadiremos nuestra función drop_duplicate_player() y le pasaremos por parámetro df

In [ ]:
def clean_data(file_path):

    df = pd.read_csv(file_path)
    df.fillna(0, inplace=True)
    df['Player'] = df.Player.apply(lambda x: x.split('\\')[0])
    df['Pos'] = df.Pos.apply(lambda x: x.split('-')[0])
    df.drop('Rk', axis=1, inplace=True)

    # Añadimos la función para el problema de los jugadores duplicados
    df = drop_duplicate_player(df)
    
    return df

Ahora simplemente pasando la ruta donde se encuentran los datos, se solucionaran automáticamente todos los problemas

In [ ]:
df = clean_data('/content/drive/MyDrive/Mi curso/Data/raw_data/nba_2019_20_pergame.csv')
df[(df.Player == 'Trevor Ariza') | (df.Player == 'Keita Bates-Diop')]

              Player Pos  Age   Tm   G  GS  ...  AST  STL  BLK  TOV   PF  PTS
18      Trevor Ariza  SF   34  TOT  53  21  ...  1.7  1.3  0.3  1.1  2.1  8.0
31  Keita Bates-Diop  PF   24  TOT  44   0  ...  0.7  0.4  0.5  0.4  1.0  6.5

[2 rows x 29 columns]

Esta es una técnica muy común, la de crear diferentes funciones y después colocarlas dentro de una función. 

# 2.2 List comprehension

¿Qué es esto de las list comprehension? No es nada más que una manera mejor y  más avanzada de realizar la técnica de la lista vacía en el bucle for. Ya hemos visto lo importante de crear una lista vacía en la cual después de un bucle for, vamos añadiendo los datos que necesitamos. Las list comprehension nos permiten realizar esta acción sin crear una lista vacía, sin utilizar .append() y ejecutando el bucle for en una sola línea de código. Veamos primero el ejemplo con el bucle for y después como podemos obtener el mismo resultado con las list comprehension.

Vamos a iterar sobre el nombre de los cinco primero jugadores del dataframe de la NBA

In [ ]:
df.loc[:5, 'Player']

0                Steven Adams
1                 Bam Adebayo
2           LaMarcus Aldridge
3              Kyle Alexander
4    Nickeil Alexander-Walker
5               Grayson Allen
Name: Player, dtype: object

Como siempre, crearemos la lista vacía y dentro del bucle for utilizaremos .append() para añadir los valores a la lista vacía.

In [ ]:
names = []
for name in df.loc[:5, 'Player']:
  names.append(name)

Ahor si miramos dentro de names, tenemos la lista con los nombres

In [ ]:
names

['Steven Adams',
 'Bam Adebayo',
 'LaMarcus Aldridge',
 'Kyle Alexander',
 'Nickeil Alexander-Walker',
 'Grayson Allen']

Vamos a ver como hacer todo este procedimiento con las list comprehension, en una sola línea de código.

In [ ]:
[name for name in df.loc[:5, 'Player']]

['Steven Adams',
 'Bam Adebayo',
 'LaMarcus Aldridge',
 'Kyle Alexander',
 'Nickeil Alexander-Walker',
 'Grayson Allen']

Hemos obtenido el mismo resultado sin tener que crear una lista vacía, ni utilizar .append(). La estructura de una list comprehension es siempre la misa:

Ejecutamos el bucle for dentro de los corchetes. 
Al principio siempre va el iterador que devolverá el bucle for. 
Por último el  bucle for de manera horizontal.


Lo que tenéis que entender es que antes de la palabra for, en la list comprehension va el iterador que en cada iteración tendrá un valor diferente y después del for, la estructura es la misma que cuando hacemos un bucle for convencional, el iterador y sobre que estamos iterando. 

Esta técnica es más eficiente que la de crear la lista vacía y utilizar .append(), ya que es más rápido y realizamos menos acciones. Al realizar el for dentro de la lista, automáticamente se está creando una lista sobre los valores que estamos iterando. Se que al principio puede costar un poco, pero su estructura siempre será la misma. A partir de ahora siempre que tengamos que usar la técnica de la lista vacía, utilizaremos las list comprehension, porque así lo hacen los profesionales y nosotros somos unos profesionales.

## 2.2.1. El condicional if dentro de la list comprehension

Hemos visto cómo utilizar los condicionales junto con el bucle for y cómo de esta manera nuestro código se hacía más poderoso. Con la list comprehension, también podemos usar los condicionales, empecemos viendo cómo usar el if.

Queremos simplemente seleccionar los valores que cumplan una condición. Acordaros, en el tema de limpieza de datos parte 2 del módulo 1, utilizamos el condicional if para encontrar las columnas que contenían el signo de porcentaje en los datos de InStat. Este fue el código que tuvimos que hacer para poder seleccionar dichas columnas.

In [ ]:
jug_2b = pd.read_csv('/content/drive/MyDrive/Mi curso/Data/raw_data/jugadores_2b.csv')

In [ ]:
cols_pct = []

for col in jug_2b.columns:
  if col.__contains__('%'):
    cols_pct.append(col)

Donde al final, dentro de la variable cols_pct teníamos las columnas que estábamos buscando.

In [ ]:
cols_pct

['%_pases', '%_aereas_ganadas', '%_Regates']

Veamos ahora cómo sería con la list comprehension:

In [ ]:
cols_pct = [col for col in jug_2b.columns if col.__contains__('%')]
cols_pct

['%_pases', '%_aereas_ganadas', '%_Regates']

Podemos ver como obtenemos exactamente el mismo resultado, añadiendo el condicional if después de la parte del bucle for.

Cuando en los datos de InStat, seleccionamos las columnas categóricas y utilizamos un bucle for y el condicional if, para añadir a una lista vacía las columnas numéricas que no se encontraban dentro de la lista de categóricas, lo hicimos de la siguiente manera:

In [ ]:
cols_cat = ['Nombre','Posición', 'Equipo','Pierna','Nacionalidad', 'Selección nacional']
cols_num = []

for col in jug_2b.columns:
  if col not in cols_cat:
    cols_num.append(col)

cols_num[:5]

['PJ', 'Goles', 'Asistencias', 'Tiros', 'TP']

Veamos como sería con la list comprehension:

In [ ]:
cols_num = [col for col in jug_2b.columns if col not in cols_cat]
cols_num[:5]

['PJ', 'Goles', 'Asistencias', 'Tiros', 'TP']

La estructura interna de una list comprehension siempre será la misma:

1. Abrimos corchetes. 
```python
[ ]
```


2. Colocamos el iterador, con el nombre que queramos darle.
```python
[col ]
```

3. El bucle for después del iterador.
```python
[col for col in jug_2b.columns]
```

4. Añadimos el condicional if después del bucle for
```python
[col for col in jug_2b.columns if col not in cols_cat]
```

Si no tenéis claro como llamar al iterador, empezad con el bucle for, pero después acordaros de añadir siempre el iterador al principio de los corchetes.

## 2.2.2 El condicional else dentro de la list comprehension

También podemos utilizar los condicionales if  y else conjuntamente, dentro de la list comprehensions con una pequeña modificación. Ya vimos como el if iba detrás del bucle for pero al añadir tambien un else, estos pasaran al principio de la list comprehension, vemoslo un ejemplo.

Acordaros del problema de las columnas con de los datos de FBref, en los que nos encontramos con columnas como 'Gls.1', 'Ast.1' etc. este valor de '.1' aparece porque ya existe la columna 'Gls' y al encontrarse pandas otra columna con el mismo nombre le añade un número. Estas columnas que tienen el '.1' realmente hacen referencia a las métricas por 90 minutos. Queremos convertir 'Gls.1' en 'Gls/90'. Esto se puede resolver de muchas maneras, pero vamos a utilizar las list comprehensions para poder ver como funciona if y else conjuntamente dentro de una list comprehension. 

Para el ejercicio utilizaremos los datos de fbref_premier_19.csv de la carpeta raw_data.

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Mi curso/Data/raw_data/fbref_premier_19.csv', 
                 header=1)
df.columns

Index(['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born', 'MP', 'Starts',
       'Min', '90s', 'Gls', 'Ast', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR',
       'Gls.1', 'Ast.1', 'G+A', 'G-PK.1', 'G+A-PK', 'xG', 'npxG', 'xA',
       'npxG+xA', 'xG.1', 'xA.1', 'xG+xA', 'npxG.1', 'npxG+xA.1', 'Matches'],
      dtype='object')

Podemos observar las columnas que contienen el valor '.1'. Antes de ver como hacerlo con las list comprehension, repasemos un concepto de strings. Los strings como en las listas podemos acceder a sus valores a través de sus índices, por tanto si yo quiero pasar de 'Gls.1' a 'Gls' será de la siguiente manera

In [ ]:
'Gls.1'[:3]

'Gls'

Con la técnica de los dos puntos, estamos yendo desde el principio hasta el tercer carácter de nuestro string. Pero como no sabemos realmente la longitud que puede tener el nombre de la columna, tenemos una mejor manera de obtener el mismo resultado y sin importar si el nombre de la columna tiene 2, 3 o 4 caracteres. Lo que sí estamos seguros es que, sea cual sea el nombre de la columna, los dos últimos caracteres contienen '.1' para obtener todos los caracteres menos los dos últimos, lo haremos de la siguiente manera.

In [ ]:
'Gls.1'[:-2]

'Gls'

Ahora si le sumas el siguiente string '/90', tendremos el nombre de la columna de manera correcta

In [ ]:
'Gls.1'[:-2] + '/90'

'Gls/90'

Entonces, vamos usar el condicional if, para cuando una columna cumpla la condición de que contiene '.1'  hacer la transformación que acabamos de ver y las que no la cumplan, con el else devolveremos simplemente el nombre de la columna. 

Muy importante!!, al añadir el else y el if ya no va al final de la list comprehension, si no al principio, justo después de lo que devolverá la list comprehension, al cumplirse la condición del if.

In [ ]:
cols = [col[:-2] + '/90'  if col.__contains__('.1') else col for col in df.columns]
df.columns = cols
df.columns

Index(['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born', 'MP', 'Starts',
       'Min', '90s', 'Gls', 'Ast', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR',
       'Gls/90', 'Ast/90', 'G+A', 'G-PK/90', 'G+A-PK', 'xG', 'npxG', 'xA',
       'npxG+xA', 'xG/90', 'xA/90', 'xG+xA', 'npxG/90', 'npxG+xA/90',
       'Matches'],
      dtype='object')

Como vemos las columnas ya están con su nombre correcto. Es importante entender la estructura interna de la list comprehension cuando utilizamos el if y else conjuntamente.

# 2.3 Mejorar nuestras funciones

Cuando creamos nuestra función que  automatizaba todo el proceso de limpieza de datos de Instat,  usamos la técnica de las listas vacías con la siguiente función:

In [ ]:
def clean_data_instat(df):
 
  # 1. Reemplazar los valores '-' por '0'
  df.replace('-', '0', inplace=True)

  # 2. Seleccionar las columnas que contienen porcentaje
  cols_pct = []

  for col in df.columns:
    if col.__contains__('%'):
      cols_pct.append(col)

  # 3. Separar el símbolo de % del número
  for col in cols_pct:
    df[col] = df[col].apply(lambda x: x.split('%')[0])

  # 4. Seleccionar las columnas numéricas
  cols_cat = ['Nombre','Posición', 'Equipo','Pierna','Nacionalidad', 'Selección nacional']
  cols_num = []

  for col in df.columns:
    if col not in cols_cat:
      cols_num.append(col)

  # 5. Aplicar pd.to_numeric() a las columnas numéricas
  for col in cols_num:
    df[col] = pd.to_numeric(df[col])

  # 6. Dividir entre 100 las columnas de porcentaje
  for col in df.columns:
    if col.__contains__('%'):
      df[col] = df[col] / 100


  return df

En todas las partes del código donde utilizamos las listas vacías, lo sustituiremos por las list comprehension que acabamos de aprender. Entonces nuestra función quedará de la siguiente manera

In [ ]:
def clean_data_instat(df):
 
  # 1. Reemplazar los valores '-' por '0'
  df.replace('-', '0', inplace=True)

  # 2. Seleccionar las columnas que contienen porcentaje
  cols_pct = [col for col in jug_2b.columns if col.__contains__('%')]

  # 3. Separar el símbolo de % del número
  for col in cols_pct:
    df[col] = df[col].apply(lambda x: x.split('%')[0])

  # 4. Seleccionar las columnas numéricas
  cols_cat = ['Nombre','Posición', 'Equipo','Pierna','Nacionalidad', 'Selección nacional']
  cols_num = [col for col in jug_2b.columns if col not in cols_cat]

  # 5. Aplicar pd.to_numeric() a las columnas numéricas
  for col in cols_num:
    df[col] = pd.to_numeric(df[col])

  # 6. Dividir entre 100 las columnas de porcentaje
  for col in df.columns:
    if col.__contains__('%'):
      df[col] = df[col] / 100

  return df

De esta manera obtendremos el mismo resultado con menos líneas de código y de una manera más eficiente.

In [ ]:
df = clean_data_instat(jug_2b)
df.head()

               Nombre  PJ  ...  Pases_efectivos  Titular
0         A. Quintana   6  ...              190        6
1  Mujaid Sadick Aliu  12  ...              589       12
2               Romay   5  ...              131        3
3    Alex Bergantinos  11  ...              576        8
4               Lucas  10  ...              472       10

[5 rows x 45 columns]