In [1]:
import kagglehub
import pandas as pd
import sqlite3

path = kagglehub.dataset_download("die9origephit/amazon-data-science-books")
print("Path to dataset files:", path)

# Aquí debes buscar la ruta completa al archivo CSV dentro del directorio descargado
csv_file_path = path + '/final_book_dataset_kaggle2.csv'

# Leer el archivo CSV con pandas
df = pd.read_csv(csv_file_path)

conn = sqlite3.connect(':memory:')

# Guardar el DataFrame en una tabla SQLite
df.to_sql('amazon_books', conn, index=False, if_exists='replace')

# Mostrar las primeras filas del dataset
print(df.head())

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.10), please consider upgrading to the latest version (0.3.11).
Path to dataset files: C:\Users\Javier\.cache\kagglehub\datasets\die9origephit\amazon-data-science-books\versions\4
                                               title  \
0  Data Analysis Using R (Low Priced Edition): A ...
1  Head First Data Analysis: A learner's guide to...
2  Guerrilla Data Analysis Using Microsoft Excel:...
3  Python for Data Analysis: Data Wrangling with ...
4  Excel Data Analysis For Dummies (For Dummies (...

                               author  price price (including used books)  \
0                 [ Dr Dhaval Maheta]   6.75                         6.75
1                                 NaN  33.72               21.49 - 33.72
2  [ Oz du Soleil,  and , Bill Jelen]  32.07                        32.07
3                 [ William McKinney]  53.99                        53.99
4                   [ Paul McFedries]  24.49                        24.49

  pages  avg_reviews n_reviews star5 star4 star3 star2 star1  \
0   500          4.4        23   55%   39%    6%   NaN   NaN
1   484          4.3       124   61%   20%    9%    4%    6%
2   274          4.7        10   87%   13%   NaN   NaN   NaN
3   547          4.6     1,686   75%   16%    5%    2%    2%
4   368          3.9        12   52%   17%   10%   10%   10%

                  dimensions       weight language  \
0     8.5 x 1.01 x 11 inches  2.53 pounds  English
1     8 x 0.98 x 9.25 inches  1.96 pounds  English
2  8.25 x 0.6 x 10.75 inches   1.4 pounds  English
3     7 x 1.11 x 9.19 inches  1.47 pounds  English
4  7.38 x 0.83 x 9.25 inches   1.3 pounds  English

                                           publisher         ISBN_13  \
0     Notion Press Media Pvt Ltd (November 22, 2021)  978-1685549596
1      O'Reilly Media; 1st edition (August 18, 2009)  978-0596153939
2  Holy Macro! Books; Third edition (August 1, 2022)  978-1615470747
3    O'Reilly Media; 2nd edition (November 14, 2017)  978-1491957660
4        For Dummies; 5th edition (February 3, 2022)  978-1119844426

                                                link  \
0  /Data-Analysis-Using-Low-Priced/dp/1685549594/...
1  /Head-First-Data-Analysis-statistics/dp/059615...
2  /Guerrilla-Analysis-Using-Microsoft-Excel/dp/1...
3  /Python-Data-Analysis-Wrangling-IPython/dp/149...
4  /Excel-Data-Analysis-Dummies-Computer/dp/11198...

                                       complete_link
0  https://www.amazon.com/Data-Analysis-Using-Low...
1  https://www.amazon.com/Head-First-Data-Analysi...
2  https://www.amazon.com/Guerrilla-Analysis-Usin...
3  https://www.amazon.com/Python-Data-Analysis-Wr...
4  https://www.amazon.com/Excel-Data-Analysis-Dum...

# Queries Basic
Esta consulta busca todos los libros escritos por el autor "[ Dr Dhaval Maheta]" en la tabla ``amazon_books`` y devuelve las columnas ``title``, ``price``, ``pages``, ``publisher``, y ``author`` para esos libros.

In [25]:
query1 = """
SELECT title, price, pages, publisher, author
FROM amazon_books
WHERE author = "[ Dr Dhaval Maheta]"
"""
result1 = pd.read_sql_query(query1, conn)

print(result1)

                                               title  price pages  \
0  Data Analysis Using R (Low Priced Edition): A ...   6.75   500

                                        publisher               author
0  Notion Press Media Pvt Ltd (November 22, 2021)  [ Dr Dhaval Maheta]

Esta consulta busca todos los libros que tienen un **precio menor a 10** y **menos de 200 páginas** en la tabla ``amazon_books`` y devuelve las columnas ``title``, ``price``, ``pages``, ``publisher``, y ``author`` para esos libros.

In [36]:
query2 = """
SELECT title, price, pages, publisher, author
FROM amazon_books
WHERE price < 10
AND pages < 200
"""
result2 = pd.read_sql_query(query2, conn)
print(result2)

                                                title  price  \
0   The Dropout Multi-Millionaire: 37 Business Les...   0.99
1   The Art of Statistical Thinking: Detect Misinf...   4.99
2   Statistics & Statistical Analysis Illustrated:...   3.99
3      Python Programming Exercises, Gently Explained   6.99
4            Learn Coding Basics in Hours with Python   3.99
5   100 Days of Code Learning Journal: Notebook fo...   7.00
6   A Student's Guide to Python for Physical Model...   4.95
7   Scala 3 Programming for Beginners: An Introduc...   8.99
8   Make a Raspberry Pi-Controlled Robot: Building...   9.59
9   Python Notebook: Lined Coding Notebook For Python   4.99
10  Leading a Data Driven Organization: A Practica...   2.99
11  The Revenge of Dr. von Naysayer (10) (The DATA...   6.99
12  Data Scientist Lined Notebook Data Science Jou...   7.99
13  Essential Calculus Skills Practice Workbook wi...   9.99

                      pages  \
0                       162
1                       178
2                       120
3                       160
4                       107
5                       108
6                       168
7                       176
8                       168
9     of high quality paper
10                      108
11                      128
12                      120
13                      151

                                            publisher  \
0          Bookmark Publishing House (April 30, 2021)
1    ARB Publications; 1st edition (October 13, 2022)
2                                                None
3        Independently published (September 30, 2022)
4                    Jack Stanley (November 17, 2017)
5         Independently published (November 28, 2021)
6   Princeton University Press; Revised edition (J...
7         Independently published (December 16, 2021)
8   Make Community, LLC; 1st edition (December 16,...
9             Independently published (June 13, 2022)
10                                               None
11                      Little Simon (March 21, 2023)
12        Independently published (February 21, 2021)
13                Zishka Publishing (August 16, 2018)

                                          author
0                                 [ Brian  WIll]
1                                           None
2                                           None
3                                 [ Al Sweigart]
4   [ The Tech Academy, Jack C. Stanley, et al.]
5                                [ Corinth Ruiz]
6       [ Jesse M. Kinder,  and , Philip Nelson]
7                              [ Nathan Metzler]
8                               [ Wolfram Donat]
9                              [ AI Publication]
10                             [ Gordon Summers]
11                                          None
12                     [ Data Science by Medved]
13                             [ Chris McMullen]

Esta consulta selecciona los libros que cumplen con las siguientes condiciones:

1. **El autor no es igual a** ``NaN``.
2. **El precio es menor a 10 o el número de páginas es menor a 200.**

Este es un ejemplo de cómo las condiciones **AND** y **OR** pueden combinarse para realizar consultas más flexibles y complejas.

In [43]:
query3 = """
SELECT title, price, pages, publisher, author
FROM amazon_books
WHERE NOT author = "NaN"
AND price < 10
OR pages < 200
"""
result3 = pd.read_sql_query(query3, conn)
print(result3)

                                                 title  price pages  \
0    Data Analysis Using R (Low Priced Edition): A ...   6.75   500
1    SQL for Data Analytics: Perform efficient and ...  15.97   106
2                                 Python in easy steps  10.69   192
3    Fluent Python: Clear, Concise, and Effective P...  50.99  1012
4     Python for Everybody: Exploring Data in Python 3   0.99   387
..                                                 ...    ...   ...
138                          Data Science in Education  10.50   195
139  Essential Calculus Skills Practice Workbook wi...   9.99   151
140  Decolonizing Data: Unsettling Conversations ab...  24.95   172
141  ColorWise: A Data Storyteller's Guide to the I...  29.99   165
142   Deep Learning: Engage the World Change the World   5.33   208

                                             publisher  \
0       Notion Press Media Pvt Ltd (November 22, 2021)
1         Independently published (September 21, 2022)
2    In Easy Steps Limited; 2nd edition (August 28,...
3           O'Reilly Media; 2nd edition (May 10, 2022)
4                                                 None
..                                                 ...
138             Independently published (July 5, 2022)
139                Zishka Publishing (August 16, 2018)
140    University of Toronto Press (February 15, 2022)
141    O'Reilly Media; 1st edition (December 20, 2022)
142          Corwin; First edition (December 15, 2017)

                                             author
0                               [ Dr Dhaval Maheta]
1                                   [ Chad Knowles]
2                                              None
3                                [ Luciano Ramalho]
4    [ Charles R. Severance, Aimee Andrion, et al.]
..                                              ...
138                               [ Andrea Filatro]
139                               [ Chris McMullen]
140                       [ Jacqueline M. Quinless]
141                               [ Kate Strachnyi]
142         [ Michael Fullan, Joanne Quinn, et al.]

[143 rows x 5 columns]

Esta consulta selecciona todos los libros de la tabla ``amazon_books`` que han sido escritos por **"[ Dr Dhaval Maheta]"** o **"[ Chad Knowles]"**, y devuelve las columnas ``title``, ``price``, ``pages``, ``publisher``, y ``author`` para esos libros.

Es una forma sencilla y eficiente de obtener los libros de uno o varios autores específicos usando el operador **IN**.

In [49]:
query4 = """
SELECT title, price, pages, publisher, author
FROM amazon_books
WHERE author IN ("[ Dr Dhaval Maheta]","[ Chad Knowles]")
"""
result4 = pd.read_sql_query(query4, conn)
print(result4)

                                               title  price pages  \
0  Data Analysis Using R (Low Priced Edition): A ...   6.75   500
1  SQL for Data Analytics: Perform efficient and ...  15.97   106
2  Learning SQL: The Complete and Comprehensive I...  14.97   146
3  SQL for Beginners: An Informative and In-depth...  15.89   159

                                        publisher               author
0  Notion Press Media Pvt Ltd (November 22, 2021)  [ Dr Dhaval Maheta]
1    Independently published (September 21, 2022)      [ Chad Knowles]
2      Independently published (October 23, 2022)      [ Chad Knowles]
3       Independently published (October 3, 2022)      [ Chad Knowles]

Esta consulta selecciona todos los libros de la tabla ``amazon_books`` cuyo *precio* se encuentra entre *10 y 13 unidades de la moneda* (inclusive), y devuelve las columnas ``title``, ``price``, ``pages``, ``publisher``, y ``author`` para esos libros.

El operador **BETWEEN** es útil cuando deseas trabajar con rangos de valores y lo hace más legible que usar múltiples condiciones con **AND**.

In [60]:
query5 = """
SELECT title, price, pages, publisher, author
FROM amazon_books
WHERE price BETWEEN 10 AND 13
"""
result5 = pd.read_sql_query(query5, conn)
print(result5)

                                                title  price pages  \
0                                Python in easy steps  10.69   192
1   Preparing For A Data Interview: Learn Enough P...  10.74    24
2   Machine Learning Explained The Simple Way: A B...  11.97   216
3   Excel 2023: The Ultimate Guide For Beginners T...  12.99   129
4   Microsoft Office 365 for Beginners: 12 Books I...  12.99   300
5   R for Data Analysis in easy steps - R Programm...  12.99   192
6   Data Structures and Algorithm Analysis in Java...  10.64   608
7   Investing for Young Adults: How to Earn, Save,...  11.89   143
8   Ball Pythons as Pets - Your Complete Owners Gu...  11.97    56
9   Aprende Python en un fin de semana (Spanish Ed...  10.04   174
10  The Computer Programming Bible: A Step by Step...  12.74   231
11  Coding for Kids: Python: Learn to Code with 50...  12.73   232
12  The Science of Football: The Math, Technology,...  10.99   236
13  Making Numbers Count: The Art and Science of C...  11.99   208
14  The Science of Hockey: The Math, Technology, a...  10.99  None
15                      The Foundations of Statistics  11.89   310
16                          Data Science in Education  10.50   195

                                            publisher  \
0   In Easy Steps Limited; 2nd edition (August 28,...
1         Independently published (December 10, 2022)
2          Independently published (October 31, 2022)
3         Independently published (November 14, 2022)
4                                                   ;
5              In Easy Steps Limited (March 13, 2018)
6   Dover Publications; Third edition (September 1...
7                     Canyon Press (October 30, 2022)
8   CreateSpace Independent Publishing Platform (N...
9           Independently published (August 30, 2018)
10         Independently published (January 16, 2020)
11                   Rockridge Press (March 19, 2019)
12              Sports Publishing (September 6, 2022)
13  Avid Reader Press / Simon & Schuster (January ...
14                Sports Publishing (January 3, 2023)
15  Dover Publications; 2nd Revised ed. edition (J...
16             Independently published (July 5, 2022)

                                   author
0                                    None
1                         [ Jonelle Hoop]
2                      [ Santos Ozoemena]
3                      [ Arthur Fletcher]
4                           [ Jamie Keet]
5                                    None
6                                    None
7                         [ Kris Pearson]
8                [ Jacqueline Silverdale]
9                                    None
10                           [ C.P.A Inc]
11                      [ Adrienne Tacke]
12  [ Will Carroll, Tyler Brooke, et al.]
13      [ Chip Heath,  and , Karla Starr]
14        [ Kevin Snow,  and , John Vogl]
15                   [ Leonard J. Savage]
16                      [ Andrea Filatro]

Esta consulta selecciona todos los libros de la tabla ``amazon_books`` cuyo editor (publisher) comienza con la palabra **"Independently"** y devuelve las columnas ``title``, ``price``, ``pages``, ``publisher``, y ``author`` para esos libros.

El uso de **LIKE con %** es útil para realizar búsquedas parciales o patrones en texto, como encontrar todos los libros de un editor que comience con un prefijo específico.

In [64]:
query6 = """
SELECT title, price, pages, publisher, author
FROM amazon_books
WHERE publisher LIKE "Independently%"
"""
result6 = pd.read_sql_query(query6, conn)
print(result6)

                                                title  price pages  \
0   SQL for Data Analytics: Perform efficient and ...  15.97   106
1   Python para Principiantes: 2 Libros en 1: Prog...  19.38   234
2   Python Programming For Beginners: The Ultimate...  15.97    88
3   Preparing For A Data Interview: Learn Enough P...  10.74    24
4   EXCEL DATA ANALYSIS: THE ULTIMATE PRACTICAL GU...  14.00   175
..                                                ...    ...   ...
76  Machine Learning Design Interview: Machine Lea...  39.99   210
77  Data Scientist Lined Notebook Data Science Jou...   7.99   120
78  SQL for Beginners: An Informative and In-depth...  15.89   159
79                          Data Science in Education  10.50   195
80   Raise Your Analytics Game: From Excel to PowerBI  25.57   260

                                       publisher  \
0   Independently published (September 21, 2022)
1          Independently published (May 2, 2020)
2   Independently published (September 24, 2022)
3    Independently published (December 10, 2022)
4    Independently published (February 21, 2022)
..                                           ...
76      Independently published (April 29, 2022)
77   Independently published (February 21, 2021)
78     Independently published (October 3, 2022)
79        Independently published (July 5, 2022)
80        Independently published (May 25, 2022)

                                    author
0                          [ Chad Knowles]
1         [ Programming Languages Academy]
2                     [ Leonard J. Ledger]
3                          [ Jonelle Hoop]
4                           [ JOE WEBINAR]
..                                     ...
76                           [ Khang Pham]
77               [ Data Science by Medved]
78                         [ Chad Knowles]
79                       [ Andrea Filatro]
80  [ Ali Noorani,  and , Muneeba Sirshar]

[81 rows x 5 columns]

# Subquery Basic
Esta consulta selecciona todos los libros cuyo precio es superior al precio promedio de todos los libros en la base de datos. Esto se logra mediante una subconsulta que calcula el promedio de los precios (**AVG(price)**), y luego se filtran los libros cuyo precio es mayor que ese valor promedio.

Es un ejemplo de cómo usar subconsultas en SQL para realizar comparaciones con valores agregados (en este caso, el precio promedio de los libros).

In [3]:
query7 = """
SELECT title, price, pages, publisher, author
FROM amazon_books
WHERE price > (SELECT AVG(price) FROM amazon_books)
"""
result7 = pd.read_sql_query(query7, conn)
print(result7)

                                                 title   price pages  \
0    Python for Data Analysis: Data Wrangling with ...   53.99   547
1      Qualitative Data Analysis: A Methods Sourcebook   90.00   408
2          Topological Data Analysis with Applications   54.19   230
3    R in Action, Third Edition: Data analysis and ...   56.99   656
4    Quantum Machine Learning and Optimisation in F...   49.99   442
..                                                 ...     ...   ...
251  Data Structures and Algorithms with Python (Un...   59.45   378
252                         Data Science for Engineers  120.00   360
253  Quantitative Social Science: An Introduction i...   49.99   488
254                        Foundations of Data Science   51.99  None
255  Machine Learning in Finance: From Theory to Pr...   55.18   573

                                             publisher  \
0      O'Reilly Media; 2nd edition (November 14, 2017)
1    SAGE Publications, Inc; 4th edition (January 2...
2    Cambridge University Press; 1st edition (March...
3                   Manning; 3rd edition (May 3, 2022)
4                  Packt Publishing (October 31, 2022)
..                                                 ...
251        Springer; 2015th edition (January 22, 2015)
252         CRC Press; 1st edition (December 16, 2022)
253        Princeton University Press (August 2, 2022)
254                                               None
255      Springer; 1st ed. 2020 edition (July 2, 2020)

                                                author
0                                  [ William McKinney]
1     [ Matthew B. Miles, A. Michael Huberman, et al.]
2    [ Gunnar Carlsson,  and , Mikael Vejdemo-Johan...
3                                [ Robert I. Kabacoff]
4      [ Antoine Jacquier, Oleksiy Kondratyev, et al.]
..                                                 ...
251                                               None
252     [ Raghunathan Rengaswamy,  and , Resmi Suresh]
253          [ Kosuke Imai,  and , Nora Webb Williams]
254               [ Avrim Blum, John Hopcroft, et al.]
255         [ Matthew F. Dixon, Igor Halperin, et al.]

[256 rows x 5 columns]

Consulta una lista de libros de la tabla ``amazon_books`` con detalles sobre el título, precio, número de páginas, editor y autor de cada libro. Además, para cada libro, calcula el precio promedio de todos los libros disponibles en la base de datos. El resultado se muestra en una tabla con los datos solicitados y el precio promedio calculado para todos los libros.

In [7]:
query8 = """
SELECT title, price, pages, publisher, author, (SELECT AVG(price) FROM amazon_books) AS Promedio_Precio
FROM amazon_books
"""
result8 = pd.read_sql_query(query8, conn)
print(result8)

                                                 title  price pages  \
0    Data Analysis Using R (Low Priced Edition): A ...   6.75   500
1    Head First Data Analysis: A learner's guide to...  33.72   484
2    Guerrilla Data Analysis Using Microsoft Excel:...  32.07   274
3    Python for Data Analysis: Data Wrangling with ...  53.99   547
4    Excel Data Analysis For Dummies (For Dummies (...  24.49   368
..                                                 ...    ...   ...
825   Deep Learning: Engage the World Change the World   5.33   208
826  Machine Learning in Finance: From Theory to Pr...  55.18   573
827  Practical Deep Learning at Scale with MLflow: ...  44.99   288
828  Clinical Biostatistics and Epidemiology Made R...    NaN  None
829  AI and Machine Learning for Coders: A Programm...  38.49  None

                                             publisher  \
0       Notion Press Media Pvt Ltd (November 22, 2021)
1        O'Reilly Media; 1st edition (August 18, 2009)
2    Holy Macro! Books; Third edition (August 1, 2022)
3      O'Reilly Media; 2nd edition (November 14, 2017)
4          For Dummies; 5th edition (February 3, 2022)
..                                                 ...
825          Corwin; First edition (December 15, 2017)
826      Springer; 1st ed. 2020 edition (July 2, 2020)
827                    Packt Publishing (July 8, 2022)
828                                               None
829                                               None

                                         author  Promedio_Precio
0                           [ Dr Dhaval Maheta]        46.491537
1                                          None        46.491537
2            [ Oz du Soleil,  and , Bill Jelen]        46.491537
3                           [ William McKinney]        46.491537
4                             [ Paul McFedries]        46.491537
..                                          ...              ...
825     [ Michael Fullan, Joanne Quinn, et al.]        46.491537
826  [ Matthew F. Dixon, Igor Halperin, et al.]        46.491537
827       [ Yong Liu,  and , Dr. Matei Zaharia]        46.491537
828                                        None        46.491537
829                         [ Laurence Moroney]        46.491537

[830 rows x 6 columns]

# Funciones SQL
Este código obtiene información sobre los libros en la tabla ``amazon_books``, incluyendo el título, precio, número de páginas, editorial y autor. Luego, redondea el precio de cada libro a un decimal y lo presenta en la columna ``price_round``. Al final, se imprime el resultado con todos los detalles, incluyendo el precio redondeado.

In [15]:
query9 = """
SELECT title, price, pages, publisher, author, ROUND(price,1) AS price_round
FROM amazon_books
"""
result9 = pd.read_sql_query(query9, conn)
print(result9)

                                                 title  price pages  \
0    Data Analysis Using R (Low Priced Edition): A ...   6.75   500
1    Head First Data Analysis: A learner's guide to...  33.72   484
2    Guerrilla Data Analysis Using Microsoft Excel:...  32.07   274
3    Python for Data Analysis: Data Wrangling with ...  53.99   547
4    Excel Data Analysis For Dummies (For Dummies (...  24.49   368
..                                                 ...    ...   ...
825   Deep Learning: Engage the World Change the World   5.33   208
826  Machine Learning in Finance: From Theory to Pr...  55.18   573
827  Practical Deep Learning at Scale with MLflow: ...  44.99   288
828  Clinical Biostatistics and Epidemiology Made R...    NaN  None
829  AI and Machine Learning for Coders: A Programm...  38.49  None

                                             publisher  \
0       Notion Press Media Pvt Ltd (November 22, 2021)
1        O'Reilly Media; 1st edition (August 18, 2009)
2    Holy Macro! Books; Third edition (August 1, 2022)
3      O'Reilly Media; 2nd edition (November 14, 2017)
4          For Dummies; 5th edition (February 3, 2022)
..                                                 ...
825          Corwin; First edition (December 15, 2017)
826      Springer; 1st ed. 2020 edition (July 2, 2020)
827                    Packt Publishing (July 8, 2022)
828                                               None
829                                               None

                                         author  price_round
0                           [ Dr Dhaval Maheta]          6.8
1                                          None         33.7
2            [ Oz du Soleil,  and , Bill Jelen]         32.1
3                           [ William McKinney]         54.0
4                             [ Paul McFedries]         24.5
..                                          ...          ...
825     [ Michael Fullan, Joanne Quinn, et al.]          5.3
826  [ Matthew F. Dixon, Igor Halperin, et al.]         55.2
827       [ Yong Liu,  and , Dr. Matei Zaharia]         45.0
828                                        None          NaN
829                         [ Laurence Moroney]         38.5

[830 rows x 6 columns]

Existen otras funciones que se pueden agregar al select para columnas númericas como:

- TRUNCATE (elimina decimales)
- CEILING (redondear para arriba)
- FLOOR (redondear para abajo)
- ABS (muestra el valor absoluto)
- RAND (crea valores decimales aleatorios)

Tambien hay algunas que se pueden usar con columnas tipo **string**:

- LENGTH (muestra la cantidad de caracteres incluye espacios)
- UPPER (convierte el texto a mayúscula)
- LOWER (convierte el texto a minúscula)
- LTRIM/RTRIM (borra todos los espacios a la izquierda/derecha de un texto)
- LEFT (Extrae x cantidad de caracteres de una palabra por la izquierda y luego los muestra)
- RIGHT Extrae x cantidad de caracteres de una palabra por la derecha y luego los muestra)
- TRIM (quita todos los espacios de más al principio y al final)
- SUBSTRING (quita caracteres fuera del rango indicado y muestra el resultado)
- LOCATE (muestra la posición de una letra en una palabra)
- REPLACE (reemplaza un caracter o una cadena de caracteres buscando por uno nuevo)
- CONCAT (une dos cadenas)

In [21]:
query10 = """
SELECT title, price, pages, publisher, UPPER(author)
FROM amazon_books
"""
result10 = pd.read_sql_query(query10, conn)
print(result10)

                                                 title  price pages  \
0    Data Analysis Using R (Low Priced Edition): A ...   6.75   500
1    Head First Data Analysis: A learner's guide to...  33.72   484
2    Guerrilla Data Analysis Using Microsoft Excel:...  32.07   274
3    Python for Data Analysis: Data Wrangling with ...  53.99   547
4    Excel Data Analysis For Dummies (For Dummies (...  24.49   368
..                                                 ...    ...   ...
825   Deep Learning: Engage the World Change the World   5.33   208
826  Machine Learning in Finance: From Theory to Pr...  55.18   573
827  Practical Deep Learning at Scale with MLflow: ...  44.99   288
828  Clinical Biostatistics and Epidemiology Made R...    NaN  None
829  AI and Machine Learning for Coders: A Programm...  38.49  None

                                             publisher  \
0       Notion Press Media Pvt Ltd (November 22, 2021)
1        O'Reilly Media; 1st edition (August 18, 2009)
2    Holy Macro! Books; Third edition (August 1, 2022)
3      O'Reilly Media; 2nd edition (November 14, 2017)
4          For Dummies; 5th edition (February 3, 2022)
..                                                 ...
825          Corwin; First edition (December 15, 2017)
826      Springer; 1st ed. 2020 edition (July 2, 2020)
827                    Packt Publishing (July 8, 2022)
828                                               None
829                                               None

                                  UPPER(author)
0                           [ DR DHAVAL MAHETA]
1                                          None
2            [ OZ DU SOLEIL,  AND , BILL JELEN]
3                           [ WILLIAM MCKINNEY]
4                             [ PAUL MCFEDRIES]
..                                          ...
825     [ MICHAEL FULLAN, JOANNE QUINN, ET AL.]
826  [ MATTHEW F. DIXON, IGOR HALPERIN, ET AL.]
827       [ YONG LIU,  AND , DR. MATEI ZAHARIA]
828                                        None
829                         [ LAURENCE MORONEY]

[830 rows x 5 columns]

las funciones **SUBSTR, LENGTH, y INSTR** para manejar la extracción del año de la cadena de texto en tu columna. Dependiendo de cómo está estructurada la cadena (si el año está al final o dentro de paréntesis).

In [51]:
query10_2 = """
SELECT title, price, pages, publisher, SUBSTR(publisher, LENGTH(publisher) - 5 + 1, 4) AS year_publisher
FROM amazon_books
LIMIT 10
"""
result10_2 = pd.read_sql_query(query10_2, conn)
print(result10_2)

                                               title  price pages  \
0  Data Analysis Using R (Low Priced Edition): A ...   6.75   500
1  Head First Data Analysis: A learner's guide to...  33.72   484
2  Guerrilla Data Analysis Using Microsoft Excel:...  32.07   274
3  Python for Data Analysis: Data Wrangling with ...  53.99   547
4  Excel Data Analysis For Dummies (For Dummies (...  24.49   368
5  Everything Data Analytics: A Beginner's Guide ...    NaN  None
6  SQL for Data Analysis: Advanced Techniques for...  40.49   360
7    Qualitative Data Analysis: A Methods Sourcebook  90.00   408
8        Topological Data Analysis with Applications  54.19   230
9  R in Action, Third Edition: Data analysis and ...  56.99   656

                                           publisher year_publisher
0     Notion Press Media Pvt Ltd (November 22, 2021)           2021
1      O'Reilly Media; 1st edition (August 18, 2009)           2009
2  Holy Macro! Books; Third edition (August 1, 2022)           2022
3    O'Reilly Media; 2nd edition (November 14, 2017)           2017
4        For Dummies; 5th edition (February 3, 2022)           2022
5                                               None           None
6      O'Reilly Media; 1st edition (October 5, 2021)           2021
7  SAGE Publications, Inc; 4th edition (January 2...           2019
8  Cambridge University Press; 1st edition (March...           2022
9                 Manning; 3rd edition (May 3, 2022)           2022

# Agregaciones
Este código obtiene, para cada autor en la tabla ``amazon_books``, el precio total de todos sus libros (suma de los precios) y el número de libros que ha publicado (conteo de los títulos). Los resultados se agrupan por autor. Al final, el código imprime una tabla que muestra estos tres valores para cada autor: ``author``, ``precio_total`` y ``numero_libros``.

In [31]:
query11 = """
SELECT author, SUM(price) AS precio_total, COUNT(title) AS numero_libros
FROM amazon_books
GROUP BY 1
"""
result11 = pd.read_sql_query(query11, conn)
print(result11)

                                            author  precio_total  \
0                                             None       4925.06
1           [ "Cathy ONeil",  and , Rachel Schutt]         26.44
2                                  [ "Mark OShea"]         16.22
3    [ ADRIENNE HAWKES MATTHES,  and , JOHN TACKE]           NaN
4                                [ AI Publication]          4.99
..                                             ...           ...
601                               [ Yves Hilpisch]        155.53
602                             [ Zhamak Dehghani]         56.87
603                                [ Zhenya Antić]         37.99
604                                  [ tony snake]           NaN
605            [ Áine Humble,  and , Elise Radina]         35.09

     numero_libros
0              173
1                1
2                1
3                1
4                1
..             ...
601              3
602              1
603              1
604              1
605              1

[606 rows x 3 columns]

Este código obtiene, para cada autor en la tabla ``amazon_books``, el precio total de sus libros y el número de libros que ha publicado. Luego, solo muestra a aquellos autores que tienen más de 2 libros en la base de datos. Los resultados se agrupan por autor, y se calcula el precio total y el número de libros de cada uno. El filtro ``HAVING numero_libros > 2`` asegura que solo se muestren los autores con más de dos libros. Finalmente, el código imprime los resultados en forma de tabla.

In [37]:
query12 = """
SELECT author, SUM(price) AS precio_total, COUNT(title) AS numero_libros
FROM amazon_books
GROUP BY 1
HAVING numero_libros > 2
"""
result12 = pd.read_sql_query(query12, conn)
print(result12)

                   author  precio_total  numero_libros
0                    None       4925.06            173
1          [ Al Sweigart]        225.03              8
2         [ Alan Agresti]        266.48              3
3      [ Allen B. Downey]         89.68              3
4         [ Chad Knowles]         46.83              3
5         [ Eric Matthes]        126.43              4
6       [ Inc. BarCharts]         17.85              3
7            [ Jim Frost]         66.72              3
8          [ Lee Vaughan]         83.93              3
9    [ Leonard J. Ledger]         54.64              3
10  [ Paul A. Zandbergen]        151.75              3
11       [ Yves Hilpisch]        155.53              3

# Querys Complejos

In [4]:
#import pandas as pd
#import numpy as np

df_demanda = pd.read_csv(r"C:\Users\Javier\Documents\Prueba DS\SUMZ\demanda.csv")
df_cat_prod = pd.read_csv(r"C:\Users\Javier\Documents\Prueba DS\SUMZ\catalogo_productos.csv")

In [6]:
df_demanda.head()

         date  id_producto  demanda
0  2020-01-01            3      869
1  2020-01-01            4      407
2  2020-01-01            5      182
3  2020-01-01            6       91
4  2020-01-01            7      520

In [8]:
df_cat_prod.head()

,id_producto,categoria,subcategoria,tamaño,premium,marca_exclusiva,estacional,nit_proveedor
0,1,bebidas,Agua,Mediano,0.0,1,0,890900667.0
1,2,jabones,Antibacterial,Pequeño,NaN,0,0,890900667.0
2,3,bebidas,Gaseosa,Pequeño,0.0,1,0,890900667.0
3,4,congelados,Vegetales,Pequeño,0.0,1,1,890900667.0
4,5,shampoos,Acondicionador,Pequeño,0.0,1,0,890900667.0

In [10]:
# Cargar los DataFrames en tablas SQL en la base de datos en memoria
df_demanda.to_sql('demanda', conn, index=False, if_exists='replace')
df_cat_prod.to_sql('catalogo_productos', conn, index=False, if_exists='replace')

135

Este query hace una unión entre las tablas ``demanda`` y ``catalogo_productos`` usando el ``id_producto`` como clave de unión, seleccionando varias columnas de ambas tablas, y limita los resultados a solo 10 filas.

In [16]:
query13 = """
SELECT d.date, d.demanda, p.categoria, p.subcategoria, p.tamaño, p.premium, p.marca_exclusiva, p.estacional, p.nit_proveedor
FROM demanda d
LEFT JOIN catalogo_productos p ON d.id_producto = p.id_producto
LIMIT 10
"""
result13 = pd.read_sql_query(query13, conn)
print(result13)

         date  demanda                                  categoria  \
0  2020-01-01      869                                    bebidas
1  2020-01-01      407                                 congelados
2  2020-01-01      182                                   shampoos
3  2020-01-01       91                                    bebidas
4  2020-01-01      520                    panaderia_y_panificados
5  2020-01-01      154                              carnes_y_aves
6  2020-01-01      721  productos_enlatados_y_alimentos_envasados
7  2020-01-01      364                              carnes_y_aves
8  2020-01-01      424                                    bebidas
9  2020-01-01      692                                    bebidas

            subcategoria   tamaño  premium  marca_exclusiva  estacional  \
0                Gaseosa  Pequeño      0.0                1           0
1              Vegetales  Pequeño      0.0                1           1
2         Acondicionador  Pequeño      0.0                1           0
3  Cerveza Internacional  Pequeño      0.0                0           0
4                  Otros  Pequeño      0.0                1           0
5                    Res  Pequeño      0.0                0           0
6                   None  Mediano      0.0                1           0
7                  Pollo  Pequeño      0.0                0           0
8                  Vinos  Pequeño      0.0                0           0
9         Licor Nacional  Pequeño      0.0                0           0

   nit_proveedor
0    890900667.0
1    890900667.0
2    890900667.0
3    890900667.0
4    890900667.0
5    890900667.0
6    890900667.0
7    890900667.0
8    890900667.0
9    890900667.0

### ¿Cuáles son los 10 productos con mayor demanda total?

In [70]:
query14 = """
SELECT p.subcategoria, SUM(d.demanda) AS total_demanda
FROM demanda d
LEFT JOIN catalogo_productos p ON d.id_producto = p.id_producto
GROUP BY p.categoria
ORDER BY total_demanda DESC
LIMIT 10
"""
result14 = pd.read_sql_query(query14, conn)
print(result14)

     subcategoria  total_demanda
0         Gaseosa       12011506
1             Res        6597141
2            None        6531384
3           Leche        5201409
4           Arroz        3057566
5  Acondicionador        2370308
6            None        1865453
7       Enlatadas         986711
8           Otros         856878
9       Vegetales         489898

### ¿Cuál es la demanda total por categoría y subcategoría de producto?

In [74]:
query15 = """
SELECT p.categoria, p.subcategoria, SUM(d.demanda) AS total_demanda
FROM demanda d
JOIN catalogo_productos p ON d.id_producto = p.id_producto
GROUP BY p.categoria, p.subcategoria
ORDER BY total_demanda DESC
"""
result15 = pd.read_sql_query(query15, conn)
print(result15)

                                    categoria           subcategoria  \
0   productos_enlatados_y_alimentos_envasados                   None
1                                     bebidas                Gaseosa
2                                     bebidas                   Agua
3                               carnes_y_aves                  Pollo
4                               carnes_y_aves                    Res
5                           productos_lacteos                  Queso
6                                     bebidas                  Vinos
7                           productos_lacteos                  Leche
8                                     bebidas         Licor Nacional
9                               carnes_y_aves                   Pavo
10                 cereales_y_productos_secos                  Arroz
11                                    bebidas                   None
12                                   shampoos         Acondicionador
13                                   shampoos             Hidratante
14                          productos_lacteos                   None
15                 cereales_y_productos_secos                  Pasta
16                                       aseo       Cuidado personal
17                 cereales_y_productos_secos              Legumbres
18                                    bebidas       Cerveza Nacional
19                                    bebidas  Cerveza Internacional
20                                       aseo       Limpieza general
21                              carnes_y_aves                  Cerdo
22                          productos_lacteos                  Yogur
23                                   shampoos                   None
24                          frutas_y_verduras                Frescas
25                    panaderia_y_panificados               Integral
26                                       aseo                   None
27                 cereales_y_productos_secos           Frutos secos
28                                    jabones          Antibacterial
29                          frutas_y_verduras              Enlatadas
30                    panaderia_y_panificados                  Otros
31                                 congelados                   None
32                          productos_lacteos                  Crema
33                          frutas_y_verduras                   None
34                    panaderia_y_panificados                   None
35                                 congelados                Helados
36                              carnes_y_aves                   None
37                                 congelados              Vegetales

    total_demanda
0         6531384
1         3546593
2         3064786
3         2674471
4         1943256
5         1779333
6         1724173
7         1713167
8         1358631
9         1253768
10        1056922
11         989286
12         961640
13         951998
14         888803
15         825273
16         819353
17         806758
18         669280
19         658757
20         625597
21         623810
22         590232
23         456670
24         432842
25         425704
26         420503
27         368613
28         363120
29         357089
30         275404
31         240797
32         229874
33         196780
34         155770
35         152807
36         101836
37          96294

### ¿Cuál es la demanda promedio mensual por producto en los últimos 6 meses?

In [76]:
query16 = """
SELECT p.subcategoria, AVG(d.demanda) AS demanda_promedio
FROM demanda d
JOIN catalogo_productos p ON d.id_producto = p.id_producto
JOIN (
    SELECT MAX(d.date) AS max_date
    FROM demanda d
) AS fecha_maxima
WHERE d.date >= DATE(fecha_maxima.max_date, '-6 months')
GROUP BY p.subcategoria
ORDER BY demanda_promedio DESC
"""
result16 = pd.read_sql_query(query16, conn)
print(result16)

             subcategoria  demanda_promedio
0        Limpieza general        418.948276
1                   Pollo        414.082637
2                    Pavo        410.752363
3                   Pasta        410.431034
4                 Frescas        396.994186
5                Integral        396.844828
6                 Gaseosa        394.228070
7                    Agua        373.262676
8           Antibacterial        357.137143
9               Legumbres        348.668407
10                  Arroz        333.990942
11                   None        320.947033
12                  Cerdo        303.472622
13         Licor Nacional        301.920792
14             Hidratante        301.662813
15                  Vinos        293.055556
16                    Res        257.029767
17                  Otros        245.672316
18                  Queso        233.694954
19           Frutos secos        195.605187
20                  Yogur        195.025714
21  Cerveza Internacional        190.738516
22                  Leche        188.915958
23       Cuidado personal        185.400756
24         Acondicionador        171.143828
25       Cerveza Nacional        159.788571
26                Helados        157.056497
27              Vegetales        156.471698
28              Enlatadas        155.391549
29                  Crema         67.543307

### ¿Cuáles son los productos más vendidos durante temporadas estacionales?

In [78]:
query17 = """
SELECT p.subcategoria, p.categoria, SUM(d.demanda) AS demanda_estacional
FROM demanda d
JOIN catalogo_productos p ON d.id_producto = p.id_producto
WHERE p.estacional = '1'
GROUP BY p.subcategoria, p.categoria
ORDER BY demanda_estacional DESC
"""
result17 = pd.read_sql_query(query17, conn)
print(result17)

             subcategoria                                  categoria  \
0                   Vinos                                    bebidas
1               Legumbres                 cereales_y_productos_secos
2                   Arroz                 cereales_y_productos_secos
3                    None  productos_enlatados_y_alimentos_envasados
4                    None                              carnes_y_aves
5               Vegetales                                 congelados
6                 Gaseosa                                    bebidas
7   Cerveza Internacional                                    bebidas
8                   Crema                          productos_lacteos
9                   Pollo                              carnes_y_aves
10                   None                                    bebidas

    demanda_estacional
0               190330
1               147728
2               132784
3               113044
4               101836
5                96294
6                90242
7                87881
8                73054
9                38841
10               12151

### ¿Qué productos premium tienen una demanda superior a 1000 unidades?

In [80]:
query18 = """
SELECT p.subcategoria, p.marca_exclusiva, SUM(d.demanda) AS total_demanda
FROM demanda d
JOIN catalogo_productos p ON d.id_producto = p.id_producto
WHERE p.premium = '1' AND d.demanda > 1000
GROUP BY p.subcategoria, p.marca_exclusiva
ORDER BY total_demanda DESC
"""
result18 = pd.read_sql_query(query18, conn)
print(result18)

  subcategoria  marca_exclusiva  total_demanda
0      Gaseosa                1          50139
1         None                1           3147
2        Queso                1           2194

### ¿Cuáles son las categorías con la mayor cantidad de productos vendidos por proveedor?

In [83]:
query19 = """
SELECT p.nit_proveedor, p.categoria, SUM(d.demanda) AS total_demanda
FROM demanda d
JOIN catalogo_productos p ON d.id_producto = p.id_producto
GROUP BY p.nit_proveedor, p.categoria
ORDER BY total_demanda DESC
"""
result19 = pd.read_sql_query(query19, conn)
print(result19)

    nit_proveedor                                  categoria  total_demanda
0     890900667.0                                    bebidas       12011506
1     890900667.0                              carnes_y_aves        6597141
2     890900667.0  productos_enlatados_y_alimentos_envasados        6319807
3     890900667.0                          productos_lacteos        5201409
4     890900667.0                 cereales_y_productos_secos        3057566
5     890900667.0                                   shampoos        2370308
6     890900667.0                                       aseo        1865453
7     890900667.0                          frutas_y_verduras         986711
8     890900667.0                    panaderia_y_panificados         856878
9     890900667.0                                 congelados         489898
10    890900667.0                                    jabones         363120
11            NaN  productos_enlatados_y_alimentos_envasados         211577

### ¿Cuál es la tendencia de demanda del producto bebidas en los últimos 3 meses?

In [89]:
query20 = """
SELECT p.subcategoria, strftime('%Y-%m', d.date) AS mes, SUM(d.demanda) AS demanda_mensual
FROM demanda d
JOIN catalogo_productos p ON d.id_producto = p.id_producto
JOIN (
    SELECT MAX(d.date) AS max_date
    FROM demanda d
) AS fecha_maxima
WHERE p.categoria = 'bebidas' AND d.date >= DATE(fecha_maxima.max_date, '-3 months')
GROUP BY p.subcategoria, mes
ORDER BY mes
"""
result20 = pd.read_sql_query(query20, conn)
print(result20)

             subcategoria      mes  demanda_mensual
0                    None  2022-08             1778
1                    Agua  2022-08             6584
2   Cerveza Internacional  2022-08              647
3        Cerveza Nacional  2022-08              831
4                 Gaseosa  2022-08             6374
5          Licor Nacional  2022-08             2652
6                   Vinos  2022-08             3044
7                    None  2022-09            25540
8                    Agua  2022-09            78529
9   Cerveza Internacional  2022-09            14828
10       Cerveza Nacional  2022-09            16698
11                Gaseosa  2022-09            85083
12         Licor Nacional  2022-09            33034
13                  Vinos  2022-09            39063
14                   None  2022-10            20784
15                   Agua  2022-10            69872
16  Cerveza Internacional  2022-10            12694
17       Cerveza Nacional  2022-10            15030
18                Gaseosa  2022-10            71229
19         Licor Nacional  2022-10            28268
20                  Vinos  2022-10            32705
21                   None  2022-11            25002
22                   Agua  2022-11            72041
23  Cerveza Internacional  2022-11            23265
24       Cerveza Nacional  2022-11            15733
25                Gaseosa  2022-11            87294
26         Licor Nacional  2022-11            31315
27                  Vinos  2022-11            53638

### ¿Cuál es la correlación entre el tamaño del producto y la demanda?

In [94]:
query21 = """
SELECT p.tamaño, SUM(d.demanda) AS total_demanda, AVG(d.demanda) AS Promedio_demanda
FROM demanda d
JOIN catalogo_productos p ON d.id_producto = p.id_producto
GROUP BY p.tamaño
ORDER BY total_demanda DESC
"""
result21 = pd.read_sql_query(query21, conn)
print(result21)

    tamaño  total_demanda  Promedio_demanda
0  Pequeño       30853178        313.437070
1  Mediano        6585631        338.002002
2   Grande        2119540        336.434921
3     None         773025        344.946452

### ¿Cuál es la distribución de la demanda por categorías en (2021-03) específico?

In [101]:
query22 = """
SELECT p.categoria, SUM(d.demanda) AS demanda_mes
FROM demanda d
JOIN catalogo_productos p ON d.id_producto = p.id_producto
WHERE strftime('%Y-%m', d.date) = '2021-03'
GROUP BY p.categoria
ORDER BY demanda_mes DESC
"""
result22 = pd.read_sql_query(query22, conn)
print(result22)

                                    categoria  demanda_mes
0                                     bebidas       300719
1                               carnes_y_aves       166456
2                           productos_lacteos       164488
3   productos_enlatados_y_alimentos_envasados       160013
4                  cereales_y_productos_secos        66416
5                                    shampoos        63646
6                                        aseo        61190
7                           frutas_y_verduras        26480
8                     panaderia_y_panificados        23776
9                                     jabones        10565
10                                 congelados        10553

### demanda total por categoría de producto en los últimos 6 meses

In [108]:
query23 = """
WITH fecha_maxima AS (
    SELECT MAX(d.date) AS max_date
    FROM demanda d
)
SELECT p.categoria, SUM(d.demanda) AS demanda_total
FROM demanda d
JOIN catalogo_productos p ON d.id_producto = p.id_producto
JOIN fecha_maxima fm ON 1=1  -- Esto hace un "cross join" con la fecha máxima
WHERE d.date >= DATE(fm.max_date, '-6 months')
GROUP BY p.categoria
ORDER BY demanda_total DESC
"""
result23 = pd.read_sql_query(query23, conn)
print(result23)

                                    categoria  demanda_total
0                                     bebidas        1965722
1   productos_enlatados_y_alimentos_envasados        1162495
2                               carnes_y_aves        1096236
3                           productos_lacteos         597004
4                  cereales_y_productos_secos         528608
5                                    shampoos         387146
6                                        aseo         222375
7                           frutas_y_verduras         155890
8                     panaderia_y_panificados         137261
9                                  congelados          72122
10                                    jabones          62499

### Obtener productos que tienen una demanda superior a la media de su categoría

In [119]:
query24 = """
WITH demanda_categoria_promedio AS (
    SELECT p.subcategoria, AVG(d.demanda) AS demanda_promedio_categoria
    FROM demanda d
    JOIN catalogo_productos p ON d.id_producto = p.id_producto
    GROUP BY p.subcategoria
)
SELECT p.id_producto, p.subcategoria, d.demanda
FROM demanda d
JOIN catalogo_productos p ON d.id_producto = p.id_producto
JOIN demanda_categoria_promedio dc ON p.subcategoria = dc.subcategoria
WHERE d.demanda > dc.demanda_promedio_categoria
ORDER BY d.demanda DESC
"""
result24 = pd.read_sql_query(query24, conn)
print(result24)

       id_producto      subcategoria  demanda
0              101           Gaseosa     1670
1              101           Gaseosa     1596
2              101           Gaseosa     1461
3               42  Limpieza general     1460
4               20           Gaseosa     1388
...            ...               ...      ...
42288           18             Crema      103
42289           18             Crema      103
42290           18             Crema      103
42291           18             Crema      103
42292           18             Crema      103

[42293 rows x 3 columns]